stages:
  - check
  - publish

.nix-base:
  image: "nixos/nix:2.8.0"
  variables:
    NIX_CONFIG: "experimental-features = nix-command flakes"

openapi-validate:
  extends: .nix-base
  stage: check
  rules:
    - when: always
  script:
    - nix develop -c openapi-generator-cli validate -i spec/openapi.yaml

openapi-lint:
  extends: .nix-base
  stage: check
  rules:
    - when: always
  script:
    - nix develop -c npx @redocly/openapi-cli@1.0.0-beta.94 lint --config lint_config.yaml spec/openapi.yaml

publish-docs:
  extends: .nix-base
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^.*-rc\.[0-9]+$/'
      when: never
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[1-9]\.*/'
      when: on_success
  script:
    - nix develop -c scripts/publish.sh $CI_COMMIT_TAG
