stages:
  - check

.nix-base:
  image: "nixos/nix:2.8.0"
  variables:
    NIX_CONFIG: "experimental-features = nix-command flakes"

openapi-validate:
  extends: .base
  stage: check
  rules:
    - when: always
  script:
    - nix develop -c openapi-generator-cli validate -i spec/api.yaml

openapi-lint:
  extends: .base
  stage: check
  rules:
    - when: always
  script:
    - nix develop -c npx @redocly/openapi-cli@1.0.0-beta.94 lint --config lint_config.yaml spec/api.yaml
