# OpenApi header is included in this file to support code highlighting in VSCode
# This is a separate file from agent_leases because these live in a different security realm (with user login) so will be exposed in a different way.
openapi: 3.0.3
info:
  title: Management of registered agents, can be used to limit the amount of active agents.
  description: StackState does not allow unlimited agents in all cases, this api allows to register agents and maybe some metadata.
  version: "1.0.0"
paths:
  /agents:
    get:
      tags:
        - agentRegistrations
      summary: "Overview of registered agents"
      description: "Give an overview of all registered agents"
      operationId: allAgentRegistrations
      responses:
        "200":
          description: "All registered agents"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AgentRegistrations"
        "403":
          description: Forbidden
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

components:
  schemas:
    AgentId:
      type: string

    AgentRegistration:
      type: object
      properties:
        agentId:
          $ref: "#/components/schemas/AgentId"
        active:
          type: boolean
        registeredEpochMs:
          type: integer
          format: int64
        platform:
          type: string
        coreCount:
          type: integer
        memoryBytes:
          type: integer
          format: int64
        kernelVersion:
          type: string
      required:
        - agentId
        - active
        - registeredEpochMs
        - platform
        - coreCount
        - memoryBytes
        - kernelVersion

    AgentRegistrations:
      type: object
      properties:
        agents:
          type: array
          items:
            $ref: "#/components/schemas/AgentRegistration"
      required:
        - agents



