# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Anomalies API
  version: "1.0.0"
paths:
  /anomalies/export:
    get:
      tags:
        - exportAnomaly
      summary: "Export anomalies with metric history and feedback"
      description: ""
      operationId: exportAnomaly
      parameters:
        - name: startTime
          description: "Beginning of timerange of to be exported anomalies.  Timestamp in unix millis."
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: endTime
          description: "End of timerange of to be exported anomalies.  Timestamp in unix millis."
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: history
          description: "Amount of historic data, leading up to the anomaly, to be exported.  Duration in unix millis."
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: feedback
          description: "Type of filtering to do on feedback.  Filtering on feedback is currently mandatory, with only the 'present' value being supporeted (feedback is available)."
          in: query
          required: true
          schema:
            type: string
            enum: [present]
      responses:
        "200":
          description: "Export feedback on anomalies."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AnomalyWithContext"
        "413":
          description: "Too many anomalies."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TooManyAnomaliesError"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

components:
  schemas:
    AnomalyWithContext:
      properties:
        anomaly:
          $ref: "#/components/schemas/Annotation"
        data:
          items:
            $ref: "#/components/schemas/Point"
          type: array
        feedback:
          $ref: "#/components/schemas/FeedbackData"
      required:
        - anomaly
        - data
      type: object

    Point:
      properties:
        ts:
          type: integer
          format: int64
        v:
          type: number
          format: double
      required:
        - ts
        - v
      type: object

    Annotation:
      properties:
        id:
          type: string
        name:
          type: string
        reference:
          $ref: "#/components/schemas/Reference"
        identifiers:
          items:
            type: string
          type: array
        description:
          type: string
        annotationType:
          $ref: "#/components/schemas/AnnotationType"
        eventTimeInterval:
          $ref: "#/components/schemas/TimeRange"
        processedTime:
          format: int64
          type: integer
        createdTime:
          format: int64
          type: integer
        tags:
          items:
            type: string
          type: array
        data:
          $ref: "#/components/schemas/AnnotationData"
      required:
        - annotationType
        - createdTime
        - description
        - eventTimeInterval
        - id
        - identifiers
        - name
        - processedTime
        - reference
        - tags
      type: object

    AnnotationType:
      enum:
        - MetricStreamAnomaly
        - MetricStreamNoAnomaly
        - AnomalyFeedback
      type: string

    AnnotationData:
      discriminator:
        propertyName: _type
      oneOf:
        - $ref: "#/components/schemas/MetricStreamAnomalyData"
        - $ref: "#/components/schemas/MetricStreamNoAnomalyData"
        - $ref: "#/components/schemas/GenericAnnotationData"
        - $ref: "#/components/schemas/FeedbackData"
      required:
        - _type
      type: object

    MetricStreamAnomalyData:
      properties:
        _type:
          enum:
            - MetricStreamAnomalyData
          type: string
        severity:
          $ref: "#/components/schemas/AnomalySeverity"
        severityScore:
          format: double
          type: number
        checkedInterval:
          $ref: "#/components/schemas/TimeRange"
        explanation:
          type: string
        modelInfo:
          type: object
        elementName:
          type: string
        streamName:
          type: string
        query:
          $ref: "#/components/schemas/AnnotationMetricQuery"
      required:
        - _type
        - checkedInterval
        - elementName
        - explanation
        - modelInfo
        - severity
        - severityScore
        - streamName
      type: object

    AnomalySeverity:
      enum:
        - LOW
        - MEDIUM
        - HIGH
      type: string

    MetricStreamNoAnomalyData:
      type: object
      properties:
        _type:
          enum:
            - MetricStreamNoAnomalyData
          type: string
        checkedInterval:
          $ref: "#/components/schemas/TimeRange"
        explanation:
          type: string
        modelInfo:
          type: object
        query:
          $ref: "#/components/schemas/AnnotationMetricQuery"
      required:
        - _type
        - checkedInterval
        - explanation
        - modelInfo

    GenericAnnotationData:
      type: object
      properties:
        _type:
          enum:
            - GenericAnnotationData
          type: string
        annotation:
          type: object
      required:
        - _type
        - annotation

    FeedbackData:
      type: object
      properties:
        _type:
          enum:
            - FeedbackData
          type: string
        subject:
          type: string
        thumbsup:
          items:
            type: string
          type: array
        thumbsdown:
          items:
            type: string
          type: array
        comments:
          items:
            $ref: "#/components/schemas/FeedbackComment"
          type: array
        query:
          $ref: "#/components/schemas/AnnotationMetricQuery"
      required:
        - _type
        - subject
        - thumbsdown
        - thumbsup
        - comments

    TimeRange:
      properties:
        start:
          format: int64
          type: integer
        end:
          format: int64
          type: integer
      required:
        - start
        - end
      type: object

    FeedbackComment:
      properties:
        author:
          type: string
        text:
          type: string
        timestamp:
          type: integer
          format: int64
      required:
        - author
        - text
        - timestamp
      type: object

    AnnotationMetricQuery:
      properties:
        dataSourceId:
          format: int64
          type: integer
        conditions:
          items:
            $ref: "#/components/schemas/TelemetryQueryCondition"
          type: array
        aggregationMethod:
          $ref: "#/components/schemas/DownsamplingMethod"
        bucketSize:
          format: int64
          type: integer
        metricField:
          type: string
        queryHash:
          type: string
      required:
        - aggregationMethod
        - bucketSize
        - conditions
        - dataSourceId
        - queryHash
      type: object

    DownsamplingMethod:
      enum:
        - MEAN
        - PERCENTILE_25
        - PERCENTILE_50
        - PERCENTILE_75
        - PERCENTILE_90
        - PERCENTILE_95
        - PERCENTILE_98
        - PERCENTILE_99
        - MAX
        - MIN
        - SUM
        - EVENT_COUNT
        - SUM_NO_ZEROS
        - EVENT_COUNT_NO_ZEROS
      type: string

    TelemetryQueryCondition:
      properties:
        key:
          type: string
        value:
          type: string
      required:
        - key
      type: object

    Reference:
      discriminator:
        propertyName: _type
      oneOf:
        - $ref: "#/components/schemas/MetricStreamReference"
      required:
        - _type
      type: object

    MetricStreamReference:
      properties:
        _type:
          enum:
            - MetricStreamReference
          type: string
        streamNodeId:
          format: int64
          type: integer
        elementIdentifiers:
          items:
            type: string
          type: array
      required:
        - _type
        - elementIdentifiers
        - streamNodeId
      type: object

    TooManyAnomaliesError:
      type: object
      properties:
        message:
          type: string
        numberOfMatches:
          type: integer
          format: int64
        maxAllowed:
          type: integer
          format: int64
      required:
        - message
