openapi: 3.0.3
info:
  title: Argument Components
  version: "1.0.0"

components:
  schemas:
    PropagatedHealthStateValue:
      enum:
        - UNKNOWN
        - PROPAGATION_ERROR
        - DEVIATING
        - FLAPPING
        - CRITICAL
      type: string
    FailingHealthStateValue:
      enum:
        - DEVIATING
        - CRITICAL
      type: string
    ComparatorWithoutEquality:
      enum:
        - GTE
        - GT
        - LT
        - LTE
      type: string
    Argument:
      type: object
      discriminator:
        propertyName: _type
      oneOf:
        - $ref: "#/components/schemas/ArgumentBooleanVal"
        - $ref: "#/components/schemas/ArgumentComponentTypeRef"
        - $ref: "#/components/schemas/ArgumentRelationTypeRef"
        - $ref: "#/components/schemas/ArgumentQueryViewRef"
        - $ref: "#/components/schemas/ArgumentLongVal"
        - $ref: "#/components/schemas/ArgumentStructTypeVal"
        - $ref: "#/components/schemas/ArgumentDoubleVal"
        - $ref: "#/components/schemas/ArgumentStateVal"
        - $ref: "#/components/schemas/ArgumentNodeIdVal"
        - $ref: "#/components/schemas/ArgumentPropagatedHealthStateVal"
        - $ref: "#/components/schemas/ArgumentDurationVal"
        - $ref: "#/components/schemas/ArgumentStringVal"
        - $ref: "#/components/schemas/ArgumentTimeWindowVal"
        - $ref: "#/components/schemas/ArgumentComparatorWithoutEqualityVal"
        - $ref: "#/components/schemas/ArgumentFailingHealthStateVal"
        - $ref: "#/components/schemas/ArgumentPromQLMetricVal"
        - $ref: "#/components/schemas/ArgumentTopologyQueryVal"
      required:
        - _type
    ArgumentStringVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentStringVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          type: string
      required:
        - _type
        - parameter
        - value
    ArgumentDurationVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentDurationVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          type: integer
          format: int64
      required:
        - _type
        - parameter
        - value
    ArgumentTimeWindowVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentTimeWindowVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        valueMs:
          type: integer
          format: int64
          minimum: 0
      required:
        - _type
        - parameter
        - valueMs
    ArgumentFailingHealthStateVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentFailingHealthStateVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          $ref: "#/components/schemas/FailingHealthStateValue"
      required:
        - _type
        - parameter
        - value
    ArgumentComparatorWithoutEqualityVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentComparatorWithoutEqualityVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          $ref: "#/components/schemas/ComparatorWithoutEquality"
      required:
        - _type
        - parameter
        - value
    ArgumentPromQLMetricVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentPromQLMetricVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          $ref: "#/components/schemas/PromQLMetric"
      required:
        - _type
        - parameter
        - value
    ArgumentTopologyQueryVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentTopologyQueryVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        query:
          type: string
      required:
        - _type
        - parameter
        - query
    ArgumentPropagatedHealthStateVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentPropagatedHealthStateVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          $ref: "#/components/schemas/PropagatedHealthStateValue"
      required:
        - _type
        - parameter
        - value
    ArgumentNodeIdVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentNodeIdVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          type: integer
          format: int64
      required:
        - _type
        - parameter
        - value
    ArgumentStateVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentStateVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
      required:
        - _type
        - parameter
        - value
    ArgumentDoubleVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentDoubleVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          type: number
          format: double
      required:
        - _type
        - parameter
        - value
    ArgumentStructTypeVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentStructTypeVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          type: string
      required:
        - _type
        - parameter
        - value
    ArgumentLongVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentLongVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          type: integer
          format: int64
      required:
        - _type
        - parameter
        - value
    ArgumentQueryViewRef:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentQueryViewRef
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        queryView:
          type: integer
          format: int64
      required:
        - _type
        - parameter
        - queryView
    ArgumentRelationTypeRef:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentRelationTypeRef
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        relationType:
          type: integer
          format: int64
      required:
        - _type
        - parameter
        - relationType
    ArgumentBooleanVal:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentBooleanVal
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        value:
          type: boolean
      required:
        - _type
        - parameter
        - value
    ArgumentComponentTypeRef:
      type: object
      properties:
        _type:
          type: string
          enum:
            - ArgumentComponentTypeRef
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        parameter:
          type: integer
          format: int64
        componentType:
          type: integer
          format: int64
      required:
        - _type
        - parameter
        - componentType
    PromQLMetric:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - PromQLMetric
        id:
          type: integer
          format: int64
        query:
          type: string
        unit:
          type: string
        aliasTemplate:
          type: string
      required:
        - _type
        - query
        - unit
        - aliasTemplate
