# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Anomalies API
  version: "1.0.0"

components:
  schemas:
    ErrorStateValue:
      enum:
        - UNKNOWN
        - STALE_DATA_STREAM
        - STREAM_DATA_NOT_FOUND
        - DATA_SOURCE_UNREACHABLE
        - DATA_STREAM_ERROR
        - CHECK_ERROR
        - CHECK_LIMITED
        - BASELINES_ARE_DEPRECATED
      type: string
    HealthStateValue:
      enum:
        - UNKNOWN
        - CLEAR
        - DISABLED
        - DEVIATING
        - FLAPPING
        - CRITICAL
      type: string
    Check:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - Check
        arguments:
          type: array
          items:
            $ref: "arguments.api.yaml#/components/schemas/Argument"
        description:
          type: string
        function:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        name:
          type: string
        remediationHint:
          type: string
        state:
          $ref: "#/components/schemas/CheckState"
        syncCreated:
          type: boolean
      required:
        - _type
        - arguments
        - function
        - name
        - syncCreated
    CheckState:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - CheckState
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        state:
          $ref: "#/components/schemas/HealthStateValue"
        lastHealthStateChangeTimestamp:
          type: integer
          format: int64
        activeErrors:
          items:
            $ref: "#/components/schemas/CheckError"
          type: array
        source:
          type: integer
          format: int64
        stateAcknowledgement:
          $ref: "#/components/schemas/CheckStateAcknowledgement"
        detailedMessage:
          type: string
        shortMessage:
          type: string
        causingEvents:
          items:
            $ref: "events.api.yaml#/components/schemas/EventRef"
          type: array
        data:
          nullable: false
          type: object
      required:
        - _type
        - state
        - lastHealthStateChangeTimestamp
        - activeErrors
        - source
        - causingEvents
    CheckError:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - CheckError
        id:
          type: integer
          format: int64
        lastUpdateTimeStamp:
          type: integer
          format: int64
        message:
          type: string
        detailedMessage:
          type: string
        state:
          $ref: "#/components/schemas/ErrorStateValue"
      required:
        - _type
        - message
        - detailedMessage
        - state
    
    CheckStateAcknowledgement:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - CheckStateAcknowledgement
        id:
          type: integer
          format: int64
        lastUpdateTimeStamp:
          type: integer
          format: int64
        acknowledgedTimestamp:
          type: integer
          format: int64
        message:
          type: string
      required:
        - _type
        - acknowledgedTimestamp
        - message
  