# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Monitors API
  version: "1.0.0"
components:
  schemas:
    ComponentTypeRelatedResources:
      properties:
        resourceType:
          type: string
        title:
          type: string
        stql:
          type: string
        hint:
          type: string
        viewTypeIdentifier:
          type: string
      required:
        - resourceType
        - title
        - stql
