# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Monitors API
  version: "1.0.0"
paths:
  /components/{componentIdOrUrn}:
    get:
      tags:
        - component
      summary: "Get full component"
      description: "Get full component details"
      operationId: getFullComponent
      parameters:
        - $ref: "#/components/parameters/componentIdOrUrn"
        - $ref: "#/components/parameters/topologyTime"
      responses:
        "200":
          $ref: "#/components/responses/fullComponent"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /components/{componentIdOrUrn}/healthHistory:
    get:
      tags:
        - component
      summary: "Get a component health history"
      description: "Get a component health history for a defined period of time by id or identifier"
      operationId: getComponentHealthHistory
      parameters:
        - $ref: "#/components/parameters/componentIdOrUrn"
        - $ref: "#/components/parameters/startTime"
        - $ref: "#/components/parameters/endTime"
      responses:
        "200":
          $ref: "#/components/responses/componentHealthHistory"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /components/{componentIdOrUrn}/checkStates:
    get:
      tags:
        - component
      summary: "Get a component checkstates"
      description: "Get a component checkstates for a defined period of time by id or identifier"
      operationId: getComponentCheckStates
      parameters:
        - $ref: "#/components/parameters/componentIdOrUrn"
        - $ref: "#/components/parameters/startTime"
        - $ref: "#/components/parameters/endTime"
      responses:
        "200":
          $ref: "#/components/responses/componentCheckStates"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  parameters:
    componentIdOrUrn:
      in: path
      name: componentIdOrUrn
      required: true
      schema:
        $ref: "#/components/schemas/ComponentIdOrUrn"
      description: "The id or identifier (urn) of a component"
    topologyTime:
      name: topologyTime
      in: query
      description: "A timestamp at which resources will be queried. If not given the resources are queried at current time."
      required: false
      schema:
        type: integer
        format: instant
    startTime:
      name: startTime
      in: query
      description: "The start time of a time range to query resources."
      required: true
      schema:
        type: integer
        format: instant
    endTime:
      name: endTime
      in: query
      description: "The end time of a time range to query resources. If not given the endTime is set to current time."
      required: false
      schema:
        type: integer
        format: instant
  responses:
    componentHealthHistory:
      description: "Component health history"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComponentHealthHistory"
    componentCheckStates:
      description: "Checkstate Histories"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComponentCheckStates"
    fullComponent:
      description: "Full component"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FullComponent"
  schemas:
    ComponentIdOrUrn:
      type: string
      pattern: ^urn:.+|[0-9]+$
    ComponentHealthHistory:
      properties:
        startTime:
          type: integer
          format: instant
        endTime:
          type: integer
          format: instant
        healthStateChanges:
          type: array
          items:
            $ref: "#/components/schemas/ComponentHealthChange"
          description: "List of health state changes ordered from most recent to oldest."
      required:
        - startTime
        - endTime
        - healthStateChanges
    ComponentHealthChange:
      properties:
        timestamp:
          type: integer
          format: int64
        newHealth:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
      required:
        - timestamp
        - newHealth
    ComponentCheckStates:
      properties:
        checkStates:
          type: array
          items:
            $ref: "#/components/schemas/ComponentCheckState"
      required:
        - checkStates
    ComponentCheckState:
      properties:
        identifier:
          type: string
        idOrIdentifier:
          type: string
        startTime:
          type: integer
          format: instant
        endTime:
          type: integer
          format: instant
      required:
        - identifier
        - idOrIdentifier
        - startTime
        - endTime
    FullComponent:
      properties:
        typeName:
          type: string
        iconbase64:
          type: string
        data:
          $ref: "#/components/schemas/ComponentData"
        highlights:
          $ref: "#/components/schemas/ComponentTypeHighlights"
        actions:
          type: array
          items:
            $ref: "#/components/schemas/ComponentAction"
        metrics:
          type: array
          items:
            $ref: "#/components/schemas/BoundMetric"
        traces:
          $ref: "#/components/schemas/BoundTraces"
      required:
        - typeName
        - data
        - actions
        - metrics
    ComponentData:
      properties:
        id:
          type: integer
          format: int64
        identifiers:
          type: array
          items:
            type: string
        name:
          type: string
        description:
          type: string
        version:
          type: string
        tags:
          type: array
          items:
            type: string
        properties:
          type: object
          additionalProperties:
            type: string
        layerName:
          type: string
        domainName:
          type: string
        health:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
        lastUpdateTimestamp:
          type: integer
          format: int64
        synced:
          type: array
          items:
            $ref: "#/components/schemas/ExternalComponent"
      required:
        - name
        - tags
        - properties
    ExternalComponent:
      properties:
        externalId:
          type: string
        identifiers:
          type: array
          items:
            type: string
        data:
          type: object
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        elementTypeTag:
          type: string
        syncName:
          type: string
        sourceProperties:
          type: object
        status:
          type: object
      required:
        - sourceProperties
        - identifiers
        - data
        - syncName
    ComponentTypeHighlights:
      properties:
        namePlural:
          type: string
        fields:
          type: array
          items:
            $ref: "#/components/schemas/ComponentTypeField"
        about:
          $ref: "#/components/schemas/ComponentTypeAbout"
        events:
          $ref: "#/components/schemas/ComponentTypeEvents"
        showLogs:
          type: boolean
        showLastChange:
          type: boolean
        externalComponent:
          $ref: "#/components/schemas/ComponentTypeExternalComponent"
        relatedResources:
          type: array
          items:
            $ref: "#/components/schemas/ComponentTypeRelatedResources"
        metrics:
          type: array
          items:
            $ref: "#/components/schemas/ComponentHighlightMetrics"
      required:
        - namePlural
        - fields
        - about
        - events
        - showLogs
        - showLastChange
        - externalComponent
        - relatedResources
        - metrics
    ComponentTypeAbout:
      properties:
        fields:
          type: array
          items:
            type: string
      required:
        - fields
    ComponentTypeField:
      properties:
        fieldId:
          type: string
        label:
          $ref: "#/components/schemas/ComponentTypeLabel"
        valueExtractor:
          $ref: "#/components/schemas/ComponentTypeValueExtractor"
        display:
          $ref: "#/components/schemas/ComponentTypeFieldDisplay"
      required:
        - fieldId
        - label
        - valueExtractor
        - display
    ComponentTypeLabel:
      properties:
        title:
          type: string
        helpBubbleText:
          type: string
      required:
        - title
    ComponentTypeValueExtractor:
      discriminator:
        propertyName: _type
      oneOf:
        - $ref: "#/components/schemas/ComponentTypeSource"
        - $ref: "#/components/schemas/CompositeSource"
        - $ref: "#/components/schemas/ConstantSource"
        - $ref: "#/components/schemas/HealthSource"
        - $ref: "#/components/schemas/IdentifiersSource"
        - $ref: "#/components/schemas/LastUpdatedTimestampSource"
        - $ref: "#/components/schemas/NameSource"
        - $ref: "#/components/schemas/PropertySource"
        - $ref: "#/components/schemas/TagSource"
        - $ref: "#/components/schemas/TagsSource"
    ComponentTypeSource:
      properties:
        _type:
          type: string
          enum:
            - ComponentTypeSource
      required:
        - _type
    CompositeSource:
      properties:
        _type:
          type: string
          enum:
            - CompositeSource
        sources:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ComponentTypeValueExtractor"
      required:
        - _type
        - sources
    ConstantSource:
      properties:
        _type:
          type: string
          enum:
            - ConstantSource
        value:
          type: string
      required:
        - _type
        - value
    HealthSource:
      properties:
        _type:
          type: string
          enum:
            - HealthSource
      required:
        - _type
    IdentifiersSource:
      properties:
        _type:
          type: string
          enum:
            - IdentifiersSource
      required:
        - _type
    LastUpdatedTimestampSource:
      properties:
        _type:
          type: string
          enum:
            - LastUpdatedTimestampSource
      required:
        - _type
    NameSource:
      properties:
        _type:
          type: string
          enum:
            - NameSource
      required:
        - _type
    PropertySource:
      properties:
        _type:
          type: string
          enum:
            - PropertySource
        key:
          type: string
        defaultValue:
          type: string
      required:
        - _type
        - key
    TagSource:
      properties:
        _type:
          type: string
          enum:
            - TagSource
        tagName:
          type: string
      required:
        - _type
        - tagName
    TagsSource:
      properties:
        _type:
          type: string
          enum:
            - TagsSource
      required:
        - _type
    ComponentTypeFieldDisplay:
      discriminator:
        propertyName: _type
      oneOf:
        - $ref: "#/components/schemas/ComponentLinkDisplay"
        - $ref: "#/components/schemas/DurationDisplay"
        - $ref: "#/components/schemas/HealthBadgeDisplay"
        - $ref: "#/components/schemas/HealthCircleDisplay"
        - $ref: "#/components/schemas/PromQLDisplay"
        - $ref: "#/components/schemas/RatioDisplay"
        - $ref: "#/components/schemas/ReadyStatusDisplay"
        - $ref: "#/components/schemas/TagDisplay"
        - $ref: "#/components/schemas/TextDisplay"
        - $ref: "#/components/schemas/ViewTimeLink"
      required:
        - _type
    ComponentLinkDisplay:
      properties:
        _type:
          type: string
          enum:
            - ComponentLinkDisplay
      required:
        - _type
    DurationDisplay:
      properties:
        _type:
          type: string
          enum:
            - DurationDisplay
      required:
        - _type
    HealthBadgeDisplay:
      properties:
        _type:
          type: string
          enum:
            - HealthBadgeDisplay
      required:
        - _type
    HealthCircleDisplay:
      properties:
        _type:
          type: string
          enum:
            - HealthCircleDisplay
      required:
        - _type
    PromQLDisplay:
      properties:
        _type:
          type: string
          enum:
            - PromQLDisplay
      required:
        - _type
    RatioDisplay:
      properties:
        _type:
          type: string
          enum:
            - RatioDisplay
      required:
        - _type
    ReadyStatusDisplay:
      properties:
        _type:
          type: string
          enum:
            - RatioDisplay
      required:
        - _type
    TagDisplay:
      properties:
        _type:
          type: string
          enum:
            - TagDisplay
        singular:
          type: string
      required:
        - _type
    TextDisplay:
      properties:
        _type:
          type: string
          enum:
            - TextDisplay
      required:
        - _type
    ViewTimeLink:
      properties:
        _type:
          type: string
          enum:
            - ViewTimeLink
      required:
        - _type
    ComponentTypeEvents:
      properties:
        showEvents:
          type: boolean
        relatedResourcesTemplate:
          type: string
      required:
        - showEvents
    ComponentTypeExternalComponent:
      properties:
        showConfiguration:
          type: boolean
        showStatus:
          type: boolean
        externalIdSelector:
          type: string
      required:
        - showConfiguration
        - showStatus
        - externalIdSelector
    ComponentTypeRelatedResources:
      properties:
        resourceType:
          type: string
        title:
          type: string
        stql:
          type: string
        hint:
          type: string
        viewTypeIdentifier:
          type: string
      required:
        - resourceType
        - title
        - stql
    ComponentHighlightMetrics:
      properties:
        name:
          type: string
        description:
          type: string
        bindings:
          type: array
          items:
            type: string
        defaultExpanded:
          type: boolean
      required:
        - name
        - bindings
        - defaultExpanded
    ComponentAction:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name
    BoundMetric:
      properties:
        name:
          type: string
        identifier:
          type: string
        boundQueries:
          type: array
          items:
            $ref: "#/components/schemas/BoundMetricQuery"
        description:
          type: string
        unit:
          type: string
        chartType:
          $ref: "#/components/schemas/ChartType"
        alias:
          type: string
        valuation:
          $ref: "#/components/schemas/MetricValuation"
        tags:
          type: object
          additionalProperties:
            type: string
        layout: 
          $ref: "#/components/schemas/MetricBindingLayout"
        dummy:
          type: boolean
      required:
        - name
        - boundQueries
        - chartType
        - tags
    BoundMetricQuery:
      properties:
        expression:
          type: string
        alias:
          type: string
        componentIdentifierTemplate:
          type: string
        primary:
          type: boolean
      required:
        - expression
        - alias
    ChartType:
      type: string
      enum:
        - line
    MetricValuation:
      type: string
      enum:
        - higher-is-better
        - lower-is-better
    MetricBindingLayout:
      properties:
        metricPerspective: 
          $ref: "#/components/schemas/MetricPerspectiveLocation"
        componentHighlight:
          $ref: "#/components/schemas/ComponentHighlightLocation"
        componentSummary:
          $ref: "#/components/schemas/ComponentSummaryLocation"
    ComponentHighlightLocation:
      properties:
        section:
          type: string
        weight:
          type: integer
      required:
        - section
    ComponentSummaryLocation:
      properties:
        weight:
          type: integer
    MetricPerspectiveLocation:
      properties:
        tab:
          type: string
        section:
          type: string
        weight:
          type: integer
      required:
        - tab
        - section
    BoundTraces:
      properties:
        filter:
          $ref: "traces.api.yaml#/components/schemas/SpanFilter"
      required:
        - filter
