# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Monitors API
  version: "1.0.0"
paths:
  /components/{componentIdOrUrn}/healthHistory:
    get:
      tags:
        - component
      summary: "Get a component health history"
      description: "Get a component health history for a defined period of time by id"
      operationId: getComponentHealthHistory
      parameters:
        - $ref: "#/components/parameters/componentIdOrUrn"
        - $ref: "#/components/parameters/startTime"
        - $ref: "#/components/parameters/endTime"
        - $ref: "#/components/parameters/topologyTime"
      responses:
        "200":
          $ref: "#/components/responses/componentHealthHistory"
        "400":
          $ref: "#/components/responses/componentNotFoundError"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

components:
  parameters:
    componentIdOrUrn:
      in: path
      name: componentIdOrUrn
      required: true
      schema:
        $ref: "#/components/schemas/ComponentIdOrUrn"
      description: "The id or identifier (urn) of a component"
    topologyTime:
      name: topologyTime
      in: query
      description: "A timestamp at which resources will be queried. If not given the resources are queried at current time."
      required: false
      schema:
        type: integer
        format: instant
    startTime:
      name: startTime
      in: query
      description: "The start time of a time range to query resources."
      required: true
      schema:
        type: integer
        format: instant
    endTime:
      name: endTime
      in: query
      description: "The end time of a time range to query resources. If not given the endTime is set to current time."
      required: false
      schema:
        type: integer
        format: instant
  responses:
    componentNotFoundError:
      description: "Component not found error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComponentNotFoundError"
    componentHealthHistory:
      description: "Component health history"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComponentHealthHistory"
  schemas:
    ComponentIdOrUrn:
      type: string
      pattern: ^urn:.+|[0-9]+$
    ComponentId:
      type: integer
      format: int64
    StreamIds:
      type: array
      items:
        type: integer
        format: int64
    ComponentHealthHistory:
      properties:
        id:
          type: integer
          format: int64
        startTime:
          type: integer
          format: instant
        endTime:
          type: integer
          format: instant
        healthStateChanges:
          type: array
          items:
            $ref: "#/components/schemas/ComponentHealthChange"
          description: "List of health state changes ordered from most recent to oldest."
      required:
        - id
        - startTime
        - endTime
        - healthStateChanges
    ComponentHealthChange:
      properties:
        timestamp:
          type: integer
          format: int64
        newHealth:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
      required:
        - timestamp
        - newHealth
    ComponentNotFoundError:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - ComponentNotFoundError
        componentId:
          $ref: "#/components/schemas/ComponentId"
      required:
        - _type
        - componentId