# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Otel Mapping API
  version: "1.0.0"

paths:
  /component-presentations:
    get:
      tags:
        - componentPresentation
      summary: List all component presentations
      operationId: getComponentPresentations
      responses:
        "200":
          description: "A list of all Component Presentations"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ComponentPresentation"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          $ref: "#/components/responses/ComponentPresentationErrorResponse"
    put:
      tags:
        - componentPresentation
      operationId: upsertComponentPresentations
      summary: Upserts (creates/updates) a component presentation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ComponentPresentation"
      responses:
        "200":
          description: "Component presentation upserted successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComponentPresentation"
        "400":
          $ref: "#/components/responses/ComponentPresentationErrorResponse"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          $ref: "#/components/responses/ComponentPresentationErrorResponse"

  /component-presentations/{identifier}:
    parameters:
      - $ref: "#/components/parameters/identifier"
    get:
      tags:
        - componentPresentation
      operationId: getComponentPresentationByIdentifier
      summary: Get a component presentation by Identifier
      responses:
        "200":
          description: "Component presentation retrieved successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComponentPresentation"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          $ref: "#/components/responses/ComponentPresentationNotFound"
        "500":
          $ref: "#/components/responses/ComponentPresentationErrorResponse"
    delete:
      tags:
        - componentPresentation
      operationId: deleteComponentPresentationByIdentifier
      summary: Delete a component presentation by Identifier
      responses:
        "204":
          description: "Component presentation deleted successfully"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          $ref: "#/components/responses/ComponentPresentationNotFound"
        "500":
          $ref: "#/components/responses/ComponentPresentationErrorResponse"
components:
  schemas:
    PresentationName:
      type: object
      properties:
        singular:
          type: string
        plural:
          type: string
      required:
        - singular
        - plural
    PresentationOverview:
      type: object
      properties:
        title:
          type: string
        mainMenu:
          $ref: "#/components/schemas/PresentationMainMenu"
      required:
        - title
    PresentationMainMenu:
      type: object
      properties:
        group:
          type: string
        iconbase64:
          type: string
        order:
          type: number
          format: double
      required:
        - group
        - order
    ComponentPresentation:
      type: object
      properties:
        identifier:
          type: string
        name:
          type: string
        description:
          type: string
        presentation:
          $ref: "#/components/schemas/PresentationDefinition"
        expireAfterMs:
          type: integer
          format: int64
      required:
        - identifier
        - name
        - presentation
    PresentationDefinition:
      type: object
      properties:
        icon:
          type: string
        name:
          $ref: "#/components/schemas/PresentationName"
        overview:
          $ref: "#/components/schemas/PresentationOverview"
    ComponentPresentationApiError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
  responses:
    ComponentPresentationNotFound:
      description: "Component Presentation with given identifier not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComponentPresentationApiError"
    ComponentPresentationErrorResponse:
      description: "Error when handling the request on the server side."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComponentPresentationApiError"
  parameters:
    identifier:
      in: path
      name: identifier
      schema:
        type: string
      required: true
