# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Components API
  version: "1.0.0"

paths:
  /components/{componentId}/streams/latest:
    get:
      tags:
        - component
      summary: "Get the latests metrics"
      description: "Gets a top 3 metrics for a datapoint, always takes the last 15 minutes before provided timepoint"
      parameters:
        - $ref: '#/components/parameters/componentId'
        - $ref: '#/components/parameters/queryTime'
        - $ref: '#/components/parameters/streamIds'
      responses:
        "200":
          $ref: '#/components/responses/telemetryLatestSnapshotsResponse'
        "404":
          $ref: '#/components/responses/componentNotFoundError'
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

components:
  parameters:
    componentId:
      in: path
      name: componentId
      required: true
      schema:
        $ref: '#/components/schemas/ComponentId'
      description: "The Identifier of a component"
    queryTime:
      in: query
      name: queryTime
      required: true
      schema:
        $ref: '#/components/schemas/QueryTime'
      description: "A Data point for a query either point from timeline or 'now' if livemode"
    streamIds:
      in: query
      name: streamIds
      required: true
      schema:
        $ref: '#/components/schemas/StreamIds'
      description: "Ids of streams to query for"
  schemas:
    ComponentId:
      type: integer
      format: int64
    QueryTime:
      type: integer
      format: instant
    StreamIds:
      type: array
      items:
        type: integer
        format: int64
    SingleMetric:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
        value:
          type: number
      required:
        - timestamp
        - value
    LatestTelemetryStreamMetrics:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - LatestTelemetryStreamMetrics
        streamId:
          type: integer
          format: int64
        metric:
          $ref: "#/components/schemas/SingleMetric"
      required:
        - _type
        - streamId
    TelemetryLatestSnapshotsResponse:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - TelemetryLatestSnapshotsResponse
        streamSnapshots:
          type: array
          items:
            $ref: "#/components/schemas/LatestTelemetryStreamMetrics"
      required:
        - _type
        - streamSnapshots
    ComponentNotFoundError:
      type: object
      discriminator:
        propertyName: _type
      properties:
        _type:
          type: string
          enum:
            - ComponentNotFoundError
        componentId:
          $ref: "#/components/schemas/ComponentId"
      required:
        - _type
        - componentId

  responses:
    componentNotFoundError:
      description: "Component not found error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComponentNotFoundError"
    telemetryLatestSnapshotsResponse:
      description: "the latest metrics for provided stream ids"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TelemetryLatestSnapshotsResponse"

