# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Import API
  version: "1.0.0"
paths:
  /import:
    post:
      tags:
        - import
      summary: "Import settings"
      description: "Import StackState Templated JSON (STJ) setting nodes."
      operationId: importSettings
      requestBody:
        required: true
        content:
          plain/text:
            schema:
              type: string
      parameters:
        - name: timeoutSeconds
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: namespace
          in: query
          required: false
          schema:
            type: string
        - name: unlocked
          in: query
          required: false
          schema:
            type: string
            enum:
              - fail
              - skip
              - overwrite
      responses:
        "200":
          description: The full description of all imported nodes.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "400":
          description: "Failure to parse the STJ."
          content:
            application/json:
              schema:
                $ref: "generic_error_handling.xapi.yaml#/components/schemas/GenericErrorsResponse"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
