# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Kubernetes Logs API
  version: "1.0.0"

paths:
  /k8s/logs:
    get:
      tags:
        - kubernetes_logs
      summary: "Get Kubernetes logs"
      operationId: getKubernetesLogs
      parameters:
        - $ref: "#/components/parameters/from"
        - $ref: "#/components/parameters/to"
        - $ref: "#/components/parameters/pageSize"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/query"
        - $ref: "#/components/parameters/podUID"
        - $ref: "#/components/parameters/containerName"
      responses:
        "200":
          $ref: "#/components/responses/GetKubernetesLogsResult"
        "400":
          $ref: "#/components/responses/GetKubernetesLogsBadRequest"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /k8s/logs/histogram:
    get:
      tags:
        - kubernetes_logs
      summary: "Get Kubernetes logs histogram"
      operationId: getKubernetesLogsHistogram
      parameters:
        - $ref: "#/components/parameters/from"
        - $ref: "#/components/parameters/to"
        - $ref: "#/components/parameters/query"
        - $ref: "#/components/parameters/podUID"
        - $ref: "#/components/parameters/containerName"
        - $ref: "#/components/parameters/histogramBucketsCount"
      responses:
        "200":
          $ref: "#/components/responses/GetKubernetesLogsHistogramResult"
        "400":
          $ref: "#/components/responses/GetKubernetesLogsHistogramBadRequest"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /k8s/logs/autocomplete:
    get:
      tags:
        - kubernetes_logs
      summary: "Get Kubernetes logs autocomplete values"
      operationId: getKubernetesLogsAutocomplete
      parameters:
        - $ref: "#/components/parameters/from"
        - $ref: "#/components/parameters/to"
        - $ref: "#/components/parameters/podUID"
      responses:
        "200":
          $ref: "#/components/responses/GetKubernetesLogsAutocompleteResult"
        "400":
          $ref: "#/components/responses/GetKubernetesLogsAutocompleteBadRequest"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  parameters:
    from:
      name: from
      in: query
      description: "Logs initial timestamp."
      required: false
      schema: { $ref: "#/components/schemas/Instant" }
    to:
      name: to
      in: query
      description: "Logs last timestamp."
      required: false
      schema: { $ref: "#/components/schemas/Instant" }
    pageSize:
      name: pageSize
      in: query
      required: false
      description: "Maximum number of the log lines in the result."
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 25
    page:
      name: page
      in: query
      required: false
      description: "Offset for which the log lines of pageSize must be returned."
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 1
    query:
      name: query
      in: query
      required: false
      description: "Find only logs containing query text."
      schema:
        type: string
        minLength: 3
    podUID:
      name: podUID
      in: query
      required: false
      description: "Find only logs for the given pod UID."
      schema:
        type: string
        format: uuid
    containerName:
      name: containerName
      in: query
      required: false
      description: "Find only logs for the given container name."
      schema:
        type: string
    histogramBucketsCount:
      name: bucketsCount
      in: query
      required: true
      description: "The number of histogram buckets."
      schema:
        type: integer
        format: int32
  responses:
    GetKubernetesLogsResult:
      description: Get logs successful result
      content:
        application/json:
          schema: { $ref: "#/components/schemas/GetKubernetesLogsResult" }
    GetKubernetesLogsBadRequest:
      description: Can not find the requested logs because one or more request params are invalid.
      content:
        application/json:
          schema: { $ref: "#/components/schemas/GetKubernetesLogsBadRequest" }
    GetKubernetesLogsHistogramResult:
      description: Get logs histogram successful result
      content:
        application/json:
          schema: { $ref: "#/components/schemas/GetKubernetesLogsHistogramResult" }
    GetKubernetesLogsHistogramBadRequest:
      description: Can not get the logs histogram because one or more request params are invalid.
      content:
        application/json:
          schema: { $ref: "#/components/schemas/GetKubernetesLogsHistogramBadRequest" }
    GetKubernetesLogsAutocompleteResult:
      description: Get logs autocomplete successful result
      content:
        application/json:
          schema: { $ref: "#/components/schemas/GetKubernetesLogsAutocompleteResult" }
    GetKubernetesLogsAutocompleteBadRequest:
      description: Can not get the logs autocomplete values because one or more request params are invalid.
      content:
        application/json:
          schema: { $ref: "#/components/schemas/GetKubernetesLogsAutocompleteBadRequest" }
  schemas:
    Instant:
      type: integer
      format: instant
    GetKubernetesLogsResult:
      type: object
      properties:
        logs:
          type: array
          items: { $ref: "#/components/schemas/KubernetesLogRecord" }
          description: "List of log records ordered by timestamps in ascend order."
        pageSize:
          type: integer
          description: "Maximum number of the log lines in the result."
        page:
          type: integer
          description: "The requested logs page."
        matchesTotal:
          type: integer
          format: int64
          description: "The total amount of matching logs for the requested search criteria."
      required:
        - logs
        - pageSize
        - page
        - matchesTotal
    KubernetesLogRecord:
      type: object
      properties:
        timestamp: { $ref: "#/components/schemas/Instant" }
        message:
          type: string
        podName:
          type: string
        podUID:
          type: string
        containerName:
          type: string
        containerRestartCount:
          type: integer
          format: int32
      required:
        - timestamp
        - message
        - podName
        - podUID
        - containerName
        - containerRestartCount
    GetKubernetesLogsBadRequest:
      oneOf:
        - $ref: "#/components/schemas/GetKubernetesLogsInvalidTimeRange"
        - $ref: "#/components/schemas/GetKubernetesLogsInvalidPagination"
        - $ref: "#/components/schemas/GetKubernetesLogsInvalidQuery"
      discriminator:
        propertyName: _type
      required:
        - _type
    GetKubernetesLogsInvalidTimeRange:
      type: object
      properties:
        _type:
          type: string
          enum:
            - InvalidTimeRange
        message:
          type: string
        from: { $ref: "#/components/schemas/Instant" }
        to: { $ref: "#/components/schemas/Instant" }
      required:
        - _type
        - message
    GetKubernetesLogsInvalidPagination:
      type: object
      properties:
        _type:
          type: string
          enum:
            - InvalidPagination
        message:
          type: string
        pageSize:
          type: integer
        page:
          type: integer
      required:
        - _type
        - message
        - pageSize
        - page
    GetKubernetesLogsInvalidQuery:
      type: object
      properties:
        _type:
          type: string
          enum:
            - InvalidQuery
        message:
          type: string
        query:
          type: string
      required:
        - _type
        - message
        - query
    GetKubernetesLogsHistogramResult:
      type: object
      properties:
        buckets:
          type: array
          items: { $ref: "#/components/schemas/KubernetesLogHistogramBucket" }
      required:
        - buckets
    KubernetesLogHistogramBucket:
      type: object
      properties:
        timestamp: { $ref: "#/components/schemas/Instant" }
        count:
          description: "Total logs record count in the bucket."
          type: integer
        startTimeMs:
          description: "The bucket initial timestamp."
          type: integer
          format: int32
        endTimeMs:
          description: "The bucket final timestamp."
          type: integer
          format: int32
      required:
        - count
        - startTimeMs
    GetKubernetesLogsHistogramBadRequest:
      oneOf:
        - $ref: "#/components/schemas/GetKubernetesLogsHistogramInvalidTimeRange"
      discriminator:
        propertyName: _type
      required:
        - _type
    GetKubernetesLogsHistogramInvalidTimeRange:
      type: object
      properties:
        _type:
          type: string
          enum:
            - InvalidTimeRange
        message:
          type: string
        from: { $ref: "#/components/schemas/Instant" }
        to: { $ref: "#/components/schemas/Instant" }
      required:
        - _type
        - message
    GetKubernetesLogsAutocompleteResult:
      type: object
      properties:
        containerNames:
          type: array
          items:
            type: string
      required:
        - containerNames
    GetKubernetesLogsAutocompleteBadRequest:
      oneOf:
        - $ref: "#/components/schemas/GetKubernetesLogsAutocompleteInvalidTimeRange"
      discriminator:
        propertyName: _type
      required:
        - _type
    GetKubernetesLogsAutocompleteInvalidTimeRange:
      type: object
      properties:
        _type:
          type: string
          enum:
            - InvalidTimeRange
        message:
          type: string
        from: { $ref: "#/components/schemas/Instant" }
        to: { $ref: "#/components/schemas/Instant" }
      required:
        - _type
        - message
