# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Monitors API
  version: "1.0.0"
paths:
  /mainmenu:
    get:
      tags:
        - mainmenu
      summary: "Get Main Menu"
      description: "Get Main Menu"
      responses:
        "200":
          $ref: "#/components/responses/mainMenuGroup"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  responses:
    mainMenuGroup:
      description: "Main Menu"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MainMenuGroup"
  schemas:
    MainMenuGroup:
      properties:
        name:
          type: string
        identifier:
          type: string
        ownedBy:
          type: string
        optionalName:
          type: string
        description:
          type: string
        id:
          type: integer
        lastUpdateTimestamp:
          type: number
        defaultOpen:
          type: boolean
        iconbase64:
          type: string
        items:
          type: array
          items: 
            $ref: "#/components/schemas/MainMenuViewItem"
      required:
        - name
        - defaultOpen
        - iconbase64
        - items
    MainMenuViewItem:
      properties:
        viewIdentifier:
          type: string
      required:
        - viewIdentifier