# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Main Menu API
  version: "1.0.0"
paths:
  /main-menu:
    get:
      tags:
        - MainMenu
      summary: "Get Main Menu"
      description: "Get Main Menu"
      responses:
        "200":
          $ref: "#/components/responses/mainMenuGroup"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  responses:
    mainMenuGroup:
      description: "Main Menu"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/MainMenuGroup"
  schemas:
    MainMenuGroup:
      properties:
        name:
          type: string
        identifier:
          type: string
        description:
          type: string
        defaultOpen:
          type: boolean
        icon:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/MainMenuViewItem"
      required:
        - name
        - defaultOpen
        - icon
        - items
    MainMenuViewItem:
      properties:
        identifier:
          type: string
          description: Either a viewIdentifier or a componentPresentationIdentifier
        title:
          type: string
        icon:
          type: string
      required:
        - identifier
        - title
