# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Monitor URN API
  version: "1.0.0"
paths:
  /monitorUrn/{monitorUrnId}:
    get:
      tags:
        - monitorUrn
      summary: "Get a monitor"
      description: "Returns a monitor full representation"
      operationId: getMonitorByURN
      parameters:
        - $ref: "#/components/parameters/monitorUrnId"
      responses:
        "200":
          $ref: "monitors.api.yaml#/components/responses/monitor"
        "404":
          $ref: "#/components/responses/monitorIdentifierNotFoundError"
        "500":
          $ref: "monitors.api.yaml#/components/responses/monitorApiError"

    delete:
      tags:
        - monitorUrn
      summary: "Delete a monitor"
      description: "Deletes existing monitor"
      operationId: deleteMonitorByURN
      parameters:
        - $ref: "#/components/parameters/monitorUrnId"
      responses:
        "204":
          description: "Return ok"
        "404":
          $ref: "#/components/responses/monitorIdentifierNotFoundError"
        "500":
          $ref: "monitors.api.yaml#/components/responses/monitorApiError"

  /monitorUrn/{monitorUrnId}/run:
    post:
      tags:
        - monitorUrn
      parameters:
        - $ref: "#/components/parameters/monitorUrnId"
      summary: "Run a monitor"
      description: "Runs a monitor once"
      operationId: runMonitorByURN
      responses:
        "200":
          $ref: "monitors.api.yaml#/components/responses/monitorRunResult"
        "404":
          $ref: "#/components/responses/monitorIdentifierNotFoundError"
        "500":
          $ref: "monitors.api.yaml#/components/responses/monitorApiError"

  /monitorUrn/{monitorUrnId}/dryRun:
    post:
      tags:
        - monitorUrn
      parameters:
        - $ref: "#/components/parameters/monitorUrnId"
      summary: "Dry run a monitor and show a result"
      description: "Performs a dry run of a monitor without topology state modification"
      operationId: dryRunMonitorByURN
      responses:
        "200":
          $ref: "monitors.api.yaml#/components/responses/monitorRunResult"
        "404":
          $ref: "#/components/responses/monitorIdentifierNotFoundError"
        "500":
          $ref: "monitors.api.yaml#/components/responses/monitorApiError"

  /monitorUrn/{monitorUrnId}/status:
    get:
      tags:
        - monitorUrn
      summary: "Get a monitor with stream information"
      description: "Returns a monitor full representation with the stream status information"
      operationId: getMonitorWithStatusByURN
      parameters:
        - $ref: "#/components/parameters/monitorUrnId"
      responses:
        "200":
          $ref: "monitors.api.yaml#/components/responses/monitorStatus"
        "404":
          $ref: "#/components/responses/monitorIdentifierNotFoundError"
        "500":
          $ref: "monitors.api.yaml#/components/responses/monitorApiError"

components:
  parameters:
    monitorUrnId:
      in: path
      name: monitorUrnId
      required: true
      schema:
        $ref: "#/components/schemas/MonitorUrnId"
      description: "The identifier of a monitor"
  requestBodies:
  responses:
    monitor:
      description: "Full representation of a monitor"
      content:
        application/json:
          schema:
            $ref: "monitors.api.yaml#/components/schemas/Monitor"
    monitorRunResult:
      description: "Full representation of the result of a monitor run"
      content:
        application/json:
          schema:
            $ref: "monitors.api.yaml#/components/schemas/MonitorRunResult"
    monitorIdentifierNotFoundError:
      description: "monitor was not found in the database"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorIdentifierNotFoundError"
  schemas:
    MonitorUrnId:
      type: string

    MonitorIdentifierNotFoundError:
      type: object
      properties:
        _type:
          type: string
          enum:
            - MonitorIdentifierNotFoundError
        monitorIdentifier:
          $ref: "#/components/schemas/MonitorUrnId"
      required:
        - _type
        - monitorIdentifier
