# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Monitor Check Status API
  version: "1.0.0"
paths:
  /monitor/checkStatus/{identifier}:
    get:
      tags:
        - monitorCheckStatus
      summary: "Get a monitor check status"
      description: "Get a monitor check status by check state id"
      operationId: getMonitorCheckStatus
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/topologyTime"
      responses:
        "200":
          $ref: "#/components/responses/monitorCheckStatus"
        "400":
          $ref: "#/components/responses/monitorCheckStatusApiError"
        "404":
          $ref: "#/components/responses/monitorCheckStatusNotFoundError"
        "500":
          $ref: "#/components/responses/monitorCheckStatusApiError"
  /monitor/checkStatus/{identifier}/relatedFailures:
    get:
      tags:
        - monitorCheckStatus
      summary: "Get a monitor check related failures"
      description: "Get a monitor check status related failures by the check state id"
      operationId: getMonitorCheckStatusRelatedFailures
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/topologyTime"
      responses:
        "200":
          $ref: "#/components/responses/monitorCheckStatusRelatedFailures"
        "400":
          $ref: "#/components/responses/monitorCheckStatusApiError"
        "404":
          $ref: "#/components/responses/monitorCheckStatusNotFoundError"
        "500":
          $ref: "#/components/responses/monitorCheckStatusApiError"
  /monitor/checkStatus/{identifier}/healthHistory:
    get:
      tags:
        - monitorCheckStatus
      summary: "Get a monitor check health history"
      description: "Get a monitor check status health history for a defined period of time by the check state id"
      operationId: getMonitorCheckStatusHealthHistory
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/startTime"
        - $ref: "#/components/parameters/endTime"
      responses:
        "200":
          $ref: "#/components/responses/monitorCheckStatusHealthHistory"
        "400":
          $ref: "#/components/responses/monitorCheckStatusApiError"
        "500":
          $ref: "#/components/responses/monitorCheckStatusApiError"

components:
  parameters:
    id:
      in: path
      name: identifier
      required: true
      schema:
        type: string
      description: "The id of a monitor check status"
    topologyTime:
      name: topologyTime
      in: query
      description: "A timestamp at which resources will be queried. If not given the resources are queried at current time."
      required: false
      schema:
        type: integer
        format: instant
    startTime:
      name: startTime
      in: query
      description: "The start time of a time range to query resources."
      required: true
      schema:
        type: integer
        format: instant
    endTime:
      name: endTime
      in: query
      description: "The end time of a time range to query resources. If not given the endTime is set to current time."
      required: false
      schema:
        type: integer
        format: instant        
  responses:
    monitorCheckStatus:
      description: "Monitor check status"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatus"
    monitorCheckStatusRelatedFailures:
      description: "Monitor check status related failures"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatusRelatedFailures"
    monitorCheckStatusHealthHistory:
      description: "Monitor check status health history"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatusHealthHistory"
    monitorCheckStatusNotFoundError:
      description: "monitor check status was not found in the database"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatusNotFoundError"
    monitorCheckStatusApiError:
      description: "container for all error response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatusApiError"
  schemas:
    MonitorCheckStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
        identifier:
          type: string
        message:
          type: string
        reason:
          type: string
        health:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
        triggeredTimestamp:
          type: integer
          format: instant
        metrics:
          type: array
          items:
              $ref: "#/components/schemas/MonitorCheckStatusMetric"
        component:
          $ref: "#/components/schemas/MonitorCheckStatusComponent"
        monitorId:
          $ref: "common.api.yaml#/components/schemas/MonitorReferenceId"
        monitorName:
          type: string
        monitorDescription:
          type: string
        troubleshootingSteps:
          type: string
        topologyTime:
          type: integer
          format: instant
        dummy:
          type: boolean
      required:
        - id
        - identifier
        - message
        - health
        - triggeredTimestamp
        - metrics
        - monitorId
        - monitorName
        - topologyTime
        - component
        - dummy
    MonitorCheckStatusMetric:
      type: object
      properties:
        _type:
          type: string
        name:
          type: string
        description:
          type: string
        unit:
          type: string
        step:
          $ref: "prometheus.api.yaml#/components/schemas/PromStep"
        queries:
          type: array
          items:
            $ref: "#/components/schemas/MonitorCheckStatusQuery"
      required:
        - _type
        - name
        - queries
    MonitorCheckStatusQuery:
      type: object
      properties:
        query:
          type: string
        alias:
          type: string
        componentIdentifierTemplate:
          type: string
      required:
        - query
    MonitorCheckStatusRelatedFailures:
      properties:
        identifier:
          type: string
        topologyTime:
          type: integer
          format: instant
        checkStatuses:
          type: array
          items:
              $ref: "#/components/schemas/MonitorCheckStatusRelatedFailuresCheckStatus"
      required:
        - identifier
        - topologyTime
        - checkStatuses
    MonitorCheckStatusRelatedFailuresCheckStatus:
      properties:
        identifier:
          type: string
        health:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
        name:
          type: string
        component:
          $ref: "#/components/schemas/MonitorCheckStatusComponent"
        topology:
          $ref: "#/components/schemas/MonitorCheckStatusRelatedFailuresTopology"
        triggeredTimestamp:
          type: integer
          format: instant
      required:
        - identifier
        - health
        - name
        - component
        - topology
        - triggeredTimestamp
    MonitorCheckStatusComponent:
      properties:
        id:
          type: integer
          format: int64
        identifier:
          type: string
        name:
          type: string
        type:
          type: string
        icon:
          type: string
      required:
        - id
        - identifier
        - name
        - type
    MonitorCheckStatusRelatedFailuresTopology:
      properties:
        distance:
          type: integer
        relation:
          type: string
          enum:
            - SELF
            - DEPENDENCY
            - IMPACTED
            - RELATED
      required:
        - distance
        - relation
    MonitorCheckStatusHealthHistory:
      properties:
        identifier:
          type: string
        startTime:
          type: integer
          format: instant      
        endTime:
          type: integer
          format: instant
        healthStateChanges:
          type: array
          items:
            $ref: "#/components/schemas/MonitorCheckStatusHealthChange"
          description: "List of health state changes ordered from most recent to oldest."
      required:
        - identifier
        - startTime
        - endTime
        - healthStateChanges
    MonitorCheckStatusHealthChange:
      properties:
        timestamp:
          type: integer
          format: int64
        newHealth:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
      required:
        - timestamp
        - newHealth
    MonitorCheckStatusApiError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    MonitorCheckStatusNotFoundError:
      type: object
      properties:
        identifier:
          type: string
        _type:
          type: string
          enum:
            - MonitorNotFoundError
      required:
        - identifier
        - _type
