# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Monitor Check Status API
  version: "1.0.0"
paths:
  /monitor/checkStatus/{id}:
    get:
      tags:
        - monitorCheckStatus
      summary: "Get a monitor check status"
      description: "Get a monitor check status by check state id"
      operationId: getMonitorCheckStatus
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/topologyTime"
      responses:
        "200":
          $ref: "#/components/responses/monitorCheckStatus"
        "400":
          $ref: "#/components/responses/monitorCheckStatusApiError"
        "404":
          $ref: "#/components/responses/monitorCheckStatusNotFoundError"
        "500":
          $ref: "#/components/responses/monitorCheckStatusApiError"
  /monitor/checkStatus/{id}/relatedFailures:
    get:
      tags:
        - monitorCheckStatus
      summary: "Get a monitor check related failures"
      description: "Get a monitor check status related failures by the check state id"
      operationId: getMonitorCheckStatusRelatedFailures
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/topologyTime"
      responses:
        "200":
          $ref: "#/components/responses/monitorCheckStatusRelatedFailures"
        "400":
          $ref: "#/components/responses/monitorCheckStatusApiError"
        "404":
          $ref: "#/components/responses/monitorCheckStatusNotFoundError"
        "500":
          $ref: "#/components/responses/monitorCheckStatusApiError"

components:
  parameters:
    id:
      in: path
      name: id
      required: true
      schema:
        type: integer
        format: int64
      description: "The id of a monitor check status"
    topologyTime:
      name: topologyTime
      in: query
      description: "A timestamp at which resources will be queried. If not given the resources are queried at current time."
      required: false
      schema:
        type: integer
        format: instant
  responses:
    monitorCheckStatus:
      description: "Monitor check status"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatus"
    monitorCheckStatusRelatedFailures:
      description: "Monitor check status related failures"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatusRelatedFailures"
    monitorCheckStatusNotFoundError:
      description: "monitor check status was not found in the database"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatusNotFoundError"
    monitorCheckStatusApiError:
      description: "container for all error response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MonitorCheckStatusApiError"
  schemas:
    MonitorCheckStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
        checkStateId:
          type: string
        name:
          type: string
        description:
          type: string
        health:
          $ref: "checks.api.yaml#/components/schemas/HealthStateValue"
        triggeredTimestamp:
          type: integer
          format: instant
        metrics:
          type: array
          items:
              $ref: "#/components/schemas/MonitorCheckStatusMetric"
        component:
          $ref: "#/components/schemas/MonitorCheckStatusComponent"
        monitorId:
          type: integer
          format: int64
        monitorName:
          type: string
        message:
          type: string
        troubleshootingSteps:
          type: string
        topologyTime:
          type: integer
          format: instant
      required:
        - id
        - checkStateId
        - name
        - health
        - triggeredTimestamp
        - metrics
        - monitorId
        - monitorName
        - topologyTime
        - component
    MonitorCheckStatusMetric:
      type: object
      properties:
        _type:
          type: string
        name:
          type: string
        query:
          $ref: "#/components/schemas/PromqlMetricQuery"
        unit:
          type: string
      required:
        - _type
        - name
        - query
    PromqlMetricQuery:
      type: object
      properties:
        query:
          $ref: "prometheus.api.yaml#/components/schemas/PromQuery"
        description:
          type: string
        startTime:
          type: integer
          format: instant
        endTime:
          type: integer
          format: instant
        step:
          $ref: "prometheus.api.yaml#/components/schemas/PromStep"
      required:
        - query
    MonitorCheckStatusRelatedFailures:
      properties:
        checkStatusId:
          type: integer
          format: int64
        topologyTime:
          type: integer
          format: instant
        checkStatuses:
          type: array
          items:
              $ref: "#/components/schemas/MonitorCheckStatusRelatedFailuresCheckStatus"
      required:
        - checkStatusId
        - topologyTime
        - checkStatuses
    MonitorCheckStatusRelatedFailuresCheckStatus:
      properties:
        id:
          type: integer
          format: int64
        health:
          $ref: "checks.api.yaml#/components/schemas/HealthStateValue"
        name:
          type: string
        component:
          $ref: "#/components/schemas/MonitorCheckStatusComponent"
        topology:
          $ref: "#/components/schemas/MonitorCheckStatusRelatedFailuresTopology"
        triggeredTimestamp:
          type: integer
          format: instant
      required:
        - id
        - health
        - name
        - component
        - topology
        - triggeredTimestamp
    MonitorCheckStatusComponent:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
        iconbase64:
          type: string
        namespace:
          type: string
        cluster:
          type: string
      required:
        - id
        - name
        - type
    MonitorCheckStatusRelatedFailuresTopology:
      properties:
        distance:
          type: integer
        relation:
          type: string
          enum:
            - SELF
            - DEPENDENCY
            - IMPACTED
            - RELATED
      required:
        - distance
        - relation
    MonitorCheckStatusApiError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    MonitorCheckStatusNotFoundError:
      type: object
      properties:
        id:
          type: integer
          format: int64
        _type:
          type: string
          enum:
            - MonitorNotFoundError
      required:
        - id
        - _type
