# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Node API
  version: "1.0.0"
paths:
  /node:
    get:
      tags:
        - node
      summary: "Node API"
      description: "list all node types"
      operationId: nodeListTypes
      responses:
        "200":
          description: "listing of all node types"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NodeTypes"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /node/{nodeType}:
    get:
      tags:
        - node
      parameters:
        - in: path
          name: nodeType
          required: true
          schema:
            type: string
        - in: query
          name: namespace
          required: false
          schema:
            type: string
        - in: query
          name: ownedBy
          required: false
          schema:
            type: string
      summary: "Node type API"
      description: "list all nodes of that type"
      operationId: typeList
      responses:
        "200":
          description: "list of mentioned type nodes"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NodeList"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  schemas:

    NodeTypes:
      type: object
      properties:
        nodeTypes:
          type: array
          items:
            type: object
            properties:
              typeName:
                type: string
              description:
                type: string
            required:
              - typeName
              - description
      required:
        - nodeTypes
    NodeList:
      type: array
      items:
        $ref: "#/components/schemas/Node"

    Node:
      type: object
      properties:
        typeName:
          type: string
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        identifier:
          type: string
        name:
          type: string
        description:
          type: string
        ownedBy:
          type: string
        manual:
          type: boolean
        isSettingsNode:
          type: boolean
      required:
        - typeName
        - id
        - lastUpdateTimestamp
