# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Notification Channels API
  version: "1.0.0"
paths:
  /notifications/channels/slack/oauth-redirect:
    get:
      parameters:
        - $ref: "#/components/parameters/channelId"
      tags:
        - notification_channels
      summary: "Starts Slack OAuth2 flow"
      description: "Redirects to Slack to start an OAuth2 flow."
      operationId: slackOauthRedirect
      responses:
        "303":
          description: "Redirects to Slack to start an OAuth2 flow that will return to the slack channel configuration afterwards. In case of an error redirects back to the Slack channel configuration with an `error` and a `channelId` parameter."
  /notifications/channels/slack/oauth-callback:
    get:
      parameters:
        - $ref: "#/components/parameters/code"
        - $ref: "#/components/parameters/state"
      tags:
        - notification_channels
      summary: "The OAuth callback for Slack"
      description: "The OAuth callback for Slack, which is used to obtain the access token for the Slack channel."
      operationId: slackOAuthCallback
      responses:
        "303":
          description: "Redirects back to the Slack channel configuration, in case of an error it includes an `error` query parameter. If known also a `channelId` parameter will be included."
components:
  parameters:
    channelId:
      in: query
      name: channelId
      required: true
      schema:
        type: string
      description: "Channel identifier"
    code:
      in: query
      name: code
      required: true
      schema:
        type: string
      description: "OAuth code from Slack"
    state:
      in: query
      name: state
      required: true
      schema:
        type: string
      description: "State parameter that was passed to Slack, should have the same value as the one passed to Slack."
      
