# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Notification Channels API
  version: "1.0.0"
paths:
  /notifications/channels/slack/{channelId}:
    get:
      parameters:
        - $ref: "#/components/parameters/channelId"
      tags:
        - notification_channels
      summary: "Get the Slack Notification channel by id"
      description: "Get the slack notification channel by id"
      operationId: getNotificationChannel
      responses:
        "200":
          $ref: "#/components/responses/slackNotificationChannel"
        "400":
          $ref: "#/components/responses/notificationChannelError"
        "404":
          $ref: "#/components/responses/notificationChannelNotFound"
        "500":
          $ref: "#/components/responses/notificationChannelError"
    delete:
      parameters:
        - $ref: "#/components/parameters/channelId"
      tags:
        - notification_channels
      summary: "Delete the Slack Notification channel by id"
      description: "Delete the slack notification channel by id"
      operationId: deleteNotificationChannel
      responses:
        "204":
          description: "Slack notification channel is deleted."
        "400":
          $ref: "#/components/responses/notificationChannelError"
        "404":
          $ref: "#/components/responses/notificationChannelNotFound"
        "500":
          $ref: "#/components/responses/notificationChannelError"

  /notifications/channels/slack/oauth-redirect:
    get:
      parameters:
        - $ref: "#/components/parameters/redirectPath"
      tags:
        - notification_channels
      summary: "Starts Slack OAuth2 flow"
      description: "Redirects to Slack to start an OAuth2 flow."
      operationId: slackOauthRedirect
      responses:
        "302":
          description: "Redirects to Slack to start an OAuth2 flow that will return to the slack channel configuration afterwards. In case of an error redirects back to the Slack channel configuration with an `error` and a `channelId` parameter."
  /notifications/channels/slack/oauth-callback:
    get:
      parameters:
        - $ref: "#/components/parameters/code"
        - $ref: "#/components/parameters/state"
      tags:
        - notification_channels
      summary: "The OAuth callback for Slack"
      description: "The OAuth callback for Slack, which is used to obtain the access token for the Slack channel."
      operationId: slackOAuthCallback
      responses:
        "302":
          description: "Redirects back to the Slack channel configuration, in case of an error it includes an `error` query parameter. If known also a `channelId` parameter will be included."
  /notifications/channels/slack/{channelId}/listSlackChannels:
    get:
      parameters:
        - $ref: "#/components/parameters/channelId"
      tags:
        - notification_channels
      summary: "List all public Slack channels"
      description: "List all public Slack channels, used for selecting a channel for the notifications"
      operationId: listSlackChannels
      responses:
        "200":
          $ref: "#/components/responses/slackChannels"
        "400":
          $ref: "#/components/responses/notificationChannelError"
        "404":
          $ref: "#/components/responses/notificationChannelNotFound"
        "500":
          $ref: "#/components/responses/notificationChannelError"
  /notifications/channels/slack/{channelId}/joinSlackChannel:
    post:
      parameters:
        - $ref: "#/components/parameters/channelId"
      requestBody:
        $ref: "#/components/requestBodies/joinSlackChannel"
      tags:
        - notification_channels
      summary: "Join the specified Slack channel to send notifications"
      description: "Join the specified Slack channel and configure this notifiation channel to post notifications to the specified slack channel."
      operationId: joinSlackChannel
      responses:
        "200": 
          $ref: "#/components/responses/slackNotificationChannel"
        "400":
          $ref: "#/components/responses/notificationChannelError"
        "404":
          $ref: "#/components/responses/notificationChannelNotFound"
        "500":
          $ref: "#/components/responses/notificationChannelError"
  /notifications/channels/slack/{channelId}/test:
    post:
      parameters:
        - $ref: "#/components/parameters/channelId"
      tags:
        - notification_channels
      summary: "Test the Notification channel"
      description: "Test the Notification channel by sending a test message to the notification channel."
      operationId: test
      responses:
        "204": 
          description: "Successfully tested channel."
        "400":
          $ref: "#/components/responses/notificationChannelError"
        "404":
          $ref: "#/components/responses/notificationChannelNotFound"
        "500":
          $ref: "#/components/responses/notificationChannelError"
components:
  parameters:
    channelId:
      in: path
      name: channelId
      required: true
      schema: { $ref: "#/components/schemas/ChannelId" }
      description: "Channel identifier"
    notificationId:
      in: path
      name: notificationId
      required: true
      schema: { $ref: "#/components/schemas/NotificationId" }
      description: "Notification configuration identifier"
    code:
      in: query
      name: code
      required: true
      schema:
        type: string
      description: "OAuth code from Slack"
    state:
      in: query
      name: state
      required: true
      schema:
        type: string
      description: "State parameter that was passed to Slack, should have the same value as the one passed to Slack."
    redirectPath:
      in: query
      name: redirectPath
      required: true
      schema:
        type: string
      description: "After completing the oauth flow the user will be redirected back to this path, in the UI, on StackState, to continue further setup of the Slack notification channel."
  requestBodies:
    joinSlackChannel:
      description: "Provide a Slack channel id to join the specified Slack channel"
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SlackChannelId"
  responses:
    slackNotificationChannel:
      description: "Slack notification channel"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SlackNotificationChannel"
    slackChannels:
      description: "Array of all available Slack channels to which StackState can send messages."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SlackChannels"
    notificationChannelError:
      description: "Error while executing the request."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotificationChannelError"
    notificationChannelNotFound:
      description: "Notification channel was not found in the database"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotificationChannelNotFound"
  schemas:
    NotificationId:
      type: integer
      format: int64
    ChannelId:
      type: integer
      format: int64
    SlackChannels:
      type: array
      items: 
        $ref: "#/components/schemas/SlackChannel"
    SlackChannel:
      type: object
      properties:
        name: 
          type: string
        id:
          type: string
      required:
       - name
       - id
    SlackChannelId:
      type: object
      properties:
        id:
          type: string
      required:
       - id
    NotificationIdBody:
      type: object
      properties:
        id:
          type: integer
          format: int64
      required:
       - id
    NotificationChannelError:
      type: object
      properties:
        message:
          type: string
        channelId:
          type: string
        _type:
          type: string
          enum:
            - NotificationChannelError
      required:
        - message
        - _type
        - channelId
    NotificationChannelNotFound:
      type: object
      properties:
        message:
          type: string
        channelId: 
          type: string
        _type:
          type: string
          enum:
            - NotificationChannelNotFound
      required:
        - message
        - channelId
        - _type
    NotificationChannel:
      oneOf:
        - $ref: "#/components/schemas/SlackNotificationChannel"
      discriminator:
        propertyName: _type
    BaseNotificationChannel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        notificationConfigurationId:
          type: integer
          format: int64
      required:
        - id
    SlackNotificationChannel:
      allOf:
        - $ref: "#/components/schemas/BaseNotificationChannel"
        - type: object
          properties:
            _type:
              type: string
              enum: 
                - SlackNotificationChannel
            slackWorkspace:
              type: string
            slackChannel: 
              type: string
            slackChannelId:
              type: string
          required:
            - _type
            - slackWorkspace
