openapi: 3.0.3
info:
  description: StackState's Admin API specification
  version: 0.0.1
  title: StackState Admin API
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
  contact:
    name: StackState
    email: info@stackstate.com
    url: "https://stackstate.com"
  x-logo:
    url: "https://raw.githubusercontent.com/StackVista/stackstate-docs/master/resources/logo/StackState-Color-padding.png"
    href: "#top"
externalDocs:
  description: Documentation
  url: "https://docs.stackstate.com/"
paths:
  /retention/window: { $ref: "retention.api.yaml#/paths/%2Fretention%2Fwindow"}
  /retention/currentEpoch: { $ref: "retention.api.yaml#/paths/%2Fretention%2FcurrentEpoch"}
  /retention/removeExpiredData: { $ref: "retention.api.yaml#/paths/%2Fretention%2FremoveExpiredData"}
security:
  - ApiToken: []
  - ServiceToken: []
  - ServiceBearer: []
components:
  securitySchemes:
    ApiToken:
      type: apiKey
      in: header
      name: X-API-Token
    ServiceToken:
      type: apiKey
      in: header
      name: X-API-Key
    ServiceBearer:
      type: apiKey
      in: header
      name: X-API-ServiceBearer
