openapi: 3.0.3
info:
  description: |
    This API documentation page describes the SUSE Observability authorization sync API.
  version: 5.2.0
  title: SUSE Observability Authorization Sync API
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
  contact:
    name: StackState
    email: info@stackstate.com
    url: "https://stackstate.com"
  x-logo:
    url: "https://raw.githubusercontent.com/StackVista/stackstate-docs/master/resources/logo/StackState-Color-padding.png"
    href: "#top"
paths:
  /rbac/instance:
    post:
      tags:
        - authorizationSyncRbacInstance
      summary: "Create instance RBAC objects"
      operationId: ingestInstanceRBAC
      description: "Ingest RBAC data snapshots to build a scoped authorization model for data access for the server API"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "common_rbac.api.yaml#/components/schemas/RBACRequest"
      responses:
        "201":
          description: "RBAC Data accepted"
        "400":
          $ref: "common_rbac.api.yaml#/components/responses/rbacError"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /rbac/scope:
    post:
      tags:
        - authorizationSyncRbacScope
      summary: "Create scope RBAC objects"
      operationId: ingestScopeRBAC
      description: "Ingest RBAC data snapshots to build a scoped authorization model for data access for the server API"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "common_rbac.api.yaml#/components/schemas/RBACRequest"
      responses:
        "201":
          description: "RBAC Data accepted"
        "400":
          $ref: "common_rbac.api.yaml#/components/responses/rbacError"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"