openapi: 3.0.3
info:
  description: |
    This API documentation page describes the SUSE Observability receiver API.
  version: 5.2.0
  title: SUSE Observability Receiver API
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
  contact:
    name: StackState
    email: info@stackstate.com
    url: "https://stackstate.com"
  x-logo:
    url: "https://raw.githubusercontent.com/StackVista/stackstate-docs/master/resources/logo/StackState-Color-padding.png"
    href: "#top"
paths:
  /stsAgent/rbac/instance: { $ref: "receiver_rbac.api.yaml#/paths/%2FstsAgent%2Frbac%2Finstance" }
  /stsAgent/rbac/scope: { $ref: "receiver_rbac.api.yaml#/paths/%2FstsAgent%2Frbac%2Fscope" }
  /stsAgent/features: { $ref: "receiver_features.api.yaml#/paths/%2FstsAgent%2Ffeatures" }
  /stsAgent/topology: { $ref: "receiver_topo_stream.api.yaml#/paths/%2Ftopology" }
