openapi: 3.0.3
info:
  title: Overview page api.
  description: Retrieves an overview based on a viewIdentifier or a componentIdentifier.
  version: "1.0.0"

paths:
  /overview/{presentationOrViewUrn}:
    post:
      tags:
        - overview
      summary: Get overview data for components
      operationId: getOverview
      parameters:
        - $ref: "#/components/parameters/presentationOrViewUrn"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OverviewRequest'
      responses:
        '200':
          description: Overview data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OverviewPageResponse'

components:
  parameters:
    presentationOrViewUrn:
      name: presentationOrViewUrn
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/PresentationOrViewIdentifier"
      description: "A Component Presentation Identifier, legacy View URNs are be supported for backward compatibility"
  schemas:
    OverviewRequest:
      type: object
      properties:
        sessionId:
          type: string
          description: "Unique identifier for the overview session"
        topologyTime:
          type: integer
          format: instant
          description: "A timestamp at which resources will be queried. If not given the resources are queried at current time."
        filters:
          $ref: '#/components/schemas/OverviewFilters'
        pagination:
          $ref: '#/components/schemas/OverviewPaginationRequest'
        sorting:
          $ref: '#/components/schemas/OverviewSortingRequest'
      required:
        - sessionId
    OverviewFilters:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/OverviewFilter'
          description: Column filters and search
        search:
          type: string
          description: Optional search string
    OverviewFilter:
      type: object
      properties:
        columnId:
          type: string
        search:
          type: string
    OverviewPaginationRequest:
      type: object
      properties:
        cursor:
          type: string
          nullable: true
          description: Opaque cursor returned from previous request
        limit:
          type: integer
          minimum: 1
          maximum: 500
          default: 50
    OverviewSortingRequest:
      type: object
      properties:
        columnId:
          type: string
        direction:
          type: string
          enum: [asc, desc]
    PresentationOrViewIdentifier:
      type: string
      pattern: ^urn.*$
    OverviewPageResponse:
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/OverviewMetadata"
        data:
          type: array
          items:
            $ref: '#/components/schemas/OverviewRow'
        pagination:
          $ref: '#/components/schemas/PaginationResponse'
    OverviewMetadata:
      type: object
      required:
        - columns
      properties:
        columns:
          type: array
          items:
            $ref: '#/components/schemas/OverviewColumnMeta'
    OverviewColumnMeta:
      type: object
      required:
        - columnId
        - title
        - display
        - sortable
        - searchable
      properties:
        columnId:
          type: string
        title:
          type: string
        display:
          $ref: '#/components/schemas/OverviewColumnMetaDisplay'
        sortable:
          type: boolean
        searchable:
          type: boolean
    OverviewColumnMetaDisplay:
      oneOf:
        - $ref: '#/components/schemas/MetricChartMetaDisplay'
        - $ref: '#/components/schemas/ComponentLinkMetaDisplay'
        - $ref: '#/components/schemas/HealthMetaDisplay'
        - $ref: '#/components/schemas/TextMetaDisplay'
        - $ref: '#/components/schemas/NumericMetaDisplay'
        - $ref: '#/components/schemas/DurationMetaDisplay'
        - $ref: '#/components/schemas/ReadyStatusMetaDisplay'
        - $ref: '#/components/schemas/ContainerImageMetaDisplay'
      discriminator:
        propertyName: _type
    MetricChartMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [MetricChartMeta]
        unit:
          type: string
          nullable: true
        decimalPlaces:
          type: integer
          nullable: true
        showChart:
          type: boolean
          nullable: true
    ComponentLinkMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [ComponentLinkMetaDisplay]
    HealthMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [HealthMetaDisplay]
    TextMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [TextMetaDisplay]
    NumericMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [NumericMetaDisplay]
        unit:
          type: string
          nullable: true
    DurationMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [DurationMetaDisplay]
    ReadyStatusMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [ReadyStatusMetaDisplay]
    ContainerImageMetaDisplay:
      type: object
      required:
        - _type
      properties:
        _type:
          type: string
          enum: [ContainerImageMetaDisplay]
    OverviewRow:
      type: object
      required:
        - componentIdentifier
        - cells
      properties:
        componentIdentifier:
          type: string

        cells:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CellValue'
    CellValue:
      oneOf:
        - $ref: '#/components/schemas/MetricCell'
        - $ref: '#/components/schemas/LinkCell'
        - $ref: '#/components/schemas/HealthCell'
        - $ref: '#/components/schemas/TextCell'
        - $ref: '#/components/schemas/NumericCell'
        - $ref: '#/components/schemas/DurationCell'
        - $ref: '#/components/schemas/ReadyStatusCell'
      discriminator:
        propertyName: _type
    MetricCell:
      type: object
      required:
        - _type
        - individualQuery
      properties:
        _type:
          enum: [MetricCell]
        individualQuery:
          type: string
          description: The frontend can use the individual query to refresh the metrics (at interval). Allows to keep the current behaviour of making individual calls for each row.
    LinkCell:
      type: object
      required:
        - _type
        - name
        - url
        - external
      properties:
        _type:
          enum: [LinkCell]
        name:
          type: string
        url:
          type: string
        external:
          type: boolean
    HealthCell:
      type: object
      required:
        - _type
        - state
      properties:
        _type:
          enum: [HealthCell]
        state:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
    TextCell:
      type: object
      required:
        - _type
        - value
      properties:
        _type:
          enum: [TextCell]
        value:
          type: string
    NumericCell:
      type: object
      required:
        - _type
        - value
      properties:
        _type:
          enum: [NumericCell]
        value:
          type: number
    DurationCell:
      type: object
      required:
        - _type
        - startDate
      properties:
        _type:
          enum: [DurationCell]
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
          nullable: true
    ReadyStatusCell:
      type: object
      required:
        - _type
        - ready
        - total
      properties:
        _type:
          enum: [DurationCell]
        ready:
          type: number
        total:
          type: number
        status:
          $ref: "common.api.yaml#/components/schemas/HealthStateValue"
    PaginationResponse:
      type: object
      properties:
        total:
          type: integer
          description: |
            Total number of items matching the ComponentPresentation
            before applying column filters or search.
        filtered:
          type: integer
          nullable: true
          description: |
            Total number of items after filters/search are applied,
            but before pagination.
        nextCursor:
          type: string
          nullable: true
      required:
        - total