# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Receiver Features Api
  version: "1.0.0"
paths:
  /stsAgent/features:
    get:
      tags:
        - features
      summary: "Get supported features from the receiver"
      description: "Get supported features from the receiver."
      operationId: getFeatures
      responses:
        "200":
          description: "Get supported features from the receiver."
          content:
            application/json:
              schema:
                type: object
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/receiverGenericErrorsResponse"
