# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Relations API
  version: "1.0.0"

paths:
  /relations/{relationId}/streams:
    get:
      tags:
        - relation
      summary: "List all streams from the relation"
      description: "List all streams from the relation"
      operationId: getRelationStreams
      parameters:
      - $ref: "#/components/parameters/relationId"
      - $ref: "#/components/parameters/queryTime"
      responses:
        "200": 
          $ref: "stack_element.api.yaml#/components/responses/telemetryStreamDefinitionCollection"
        "404":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/stackElementNotFound" 
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /relations/{relationId}/streams/{streamId}:
    get:
      tags:
        - relation
      summary: "Get the stream from the relation"
      description: "Get a Specific stream from the relation"
      operationId: getRelationStream
      parameters:
        - $ref: "#/components/parameters/relationId"
        - $ref: "#/components/parameters/queryTime"
        - $ref: "#/components/parameters/streamId"
      responses:
        "200": 
          $ref: "stack_element.api.yaml#/components/responses/telemetryStreamDefinition"
        "404":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/stackElementNotFound"  
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /relations/{relationId}/checks:
    get:
      tags:
        - relation
      summary: "List all checks from the relation"
      description: "List all checks from the relation"
      parameters:
        - $ref: "#/components/parameters/relationId"
        - $ref: "#/components/parameters/queryTime"
      operationId: "getRelationChecks"
      responses:
        "200": 
          $ref: "stack_element.api.yaml#/components/responses/elementCheckCollection"
        "404":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/stackElementNotFound" 
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /relations/{relationId}/checks/{checkId}:
    get:
      tags:
        - relation
      summary: "Get the check from the relation"
      description: "Get a Specific check from the relation"
      operationId: "getRelationCheck"
      parameters:
        - $ref: "#/components/parameters/relationId"
        - $ref: "#/components/parameters/queryTime"
        - $ref: "#/components/parameters/checkId"
      responses:
        "200": 
          $ref: "stack_element.api.yaml#/components/responses/elementCheck"
        "404":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/stackElementNotFound" 
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  parameters:
    relationId:
      in: path
      name: relationId
      required: true
      schema:
        $ref: '#/components/schemas/RelationId'
      description: "The Identifier of a relation"
    streamId:
      in: path
      name: streamId
      required: true
      schema:
        $ref: "stack_element.api.yaml#/components/schemas/StreamId"
      description: "The Identifier of a stream"
    checkId:
      in: path
      name: checkId
      required: true
      schema:
        $ref: "stack_element.api.yaml#/components/schemas/CheckId"
      description: "The Identifier of a Check"
    queryTime:
      in: query
      name: queryTime
      required: true
      schema:
        $ref: "stack_element.api.yaml#/components/schemas/QueryTime"
      description: "A Data point for a query either point from timeline or 'now' if livemode"
  schemas:
    RelationId:
      type: integer
      format: int64
