openapi: 3.0.0
info:
  title: Snapshot API
  version: 1.0.0
  description: API for querying topology snapshots using STQL queries

paths:
  /snapshot:
    post:
      summary: Query topology snapshot
      operationId: querySnapshot
      tags:
        - snapshot
      parameters:
        - $ref: "#/components/parameters/timeout-ms"
      requestBody:
        $ref: "#/components/requestBodies/ViewSnapshotRequest"
      responses:
        '200':
          $ref: "#/components/responses/viewQuerySnapshotResult"
        '400':
          $ref: "#/components/responses/viewQueryParsingFailure"
        '401':
          description: "User is not authorized"
        '403':
          description: "User is forbidden for the provided permission"
        '500':
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

components:
  parameters:
    timeout-ms:
      name: timeout-ms
      in: query
      required: false
      schema:
        type: integer
        format: int64
        default: 30000
      description: Query timeout in milliseconds


  requestBodies:
    ViewSnapshotRequest:
      description: Request body for querying a topology snapshot
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ViewSnapshotRequest'

  responses:
    viewQuerySnapshotResult:
      description: Snapshot query result
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/QuerySnapshotResult'
    viewQueryParsingFailure:
      description: Query parsing failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/QueryParsingFailure'

  schemas:
    ViewSnapshotRequest:
      type: object
      properties:
        _type:
          type: string
          enum: [ ViewSnapshotRequest ]
        query:
          type: string
          description: STQL query string
        queryVersion:
          type: string
          pattern: '^\d+\.\d+\.\d+$'
          example: "0.0.1"
        metadata:
          $ref: '#/components/schemas/QueryMetadata'
        viewId:
          type: integer
          format: int64
          description: View identifier that gets mapped back in the response. Preserved for compatibility when this API got moved to OpenAPI. Not used for any processing.
      required:
        - _type
        - query
        - queryVersion
        - metadata

    QueryMetadata:
      type: object
      description: Query execution settings
      properties:
        groupingEnabled:
          type: boolean
        showIndirectRelations:
          type: boolean
        minGroupSize:
          type: integer
          format: int64
        groupedByLayer:
          type: boolean
        groupedByDomain:
          type: boolean
        groupedByRelation:
          type: boolean
        queryTime:
          type: integer
          format: int64
          nullable: true
          description: Unix timestamp in milliseconds
        autoGrouping:
          type: boolean
        connectedComponents:
          type: boolean
        neighboringComponents:
          type: boolean
        showFullComponent:
          type: boolean
      required:
        - groupingEnabled
        - showIndirectRelations
        - minGroupSize
        - groupedByLayer
        - groupedByDomain
        - groupedByRelation
        - autoGrouping
        - connectedComponents
        - neighboringComponents
        - showFullComponent

    QuerySnapshotResponse:
      discriminator:
        propertyName: _type
      oneOf:
        - $ref: '#/components/schemas/QueryParsingFailure'
        - $ref: '#/components/schemas/QuerySnapshotResult'

    QueryParsingFailure:
      type: object
      description: |
        Query parsing failed. The reason field contains the error message.
      properties:
        _type:
          type: string
          enum:
            - QueryParsingFailure
          description: Discriminator field
        reason:
          type: string
          description: Error message describing why the query failed to parse
      required:
        - _type
        - reason

    QuerySnapshotResult:
      type: object
      description: |
        Query succeeded (or encountered a runtime error that's part of the result).
        The SnapshotResponse uses existing DTO types for nested structures.
      properties:
        _type:
          type: string
          enum:
            - QuerySnapshotResult
          description: Discriminator field
        viewSnapshotResponse:
          type: object
          description: |
            The query result or error response. This is opaque at the API level but contains one of the following DTO types:
            - ViewSnapshot (success)
            - ViewSnapshotFetchTimeout (error)
            - ViewSnapshotTooManyActiveQueries (error)
            - ViewSnapshotTopologySizeOverflow (error)
            - ViewSnapshotDataUnavailable (error)
            Use the _type field to discriminate between types.
        viewId:
          type: integer
          format: int64
          description: View identifier that was provided in the ViewSnapshotRequest. Preserved for compatibility when this API got moved to OpenAPI. Not used for any processing.
      required:
        - _type
        - viewSnapshotResponse
