# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: StackPack API
  version: "1.0.0"
paths:
  /stackpack:
    post:
      tags:
        - stackpack
      summary: "StackPack API"
      operationId: stackPackUpload
      description: "upload a StackPack"
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/StackPackUpload"
      responses:
        "202":
          description: "Upload success. Processing happens asynchronously."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackPack"
        "400":
          description: "bad request"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
    get:
      tags:
        - stackpack
      summary: "StackPack API"
      operationId: stackPackList
      description: "list of stackpack"
      responses:
        "200":
          description: "Get list of stackpack"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackPackList"
        "400":
          description: "bad request"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /stackpack/{stackPackName}/provision:
    post:
      tags:
        - stackpack
      parameters:
        - $ref: "#/components/parameters/stackPackName"
      summary: "Provision API"
      operationId: provisionDetails
      description: "Provision details"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        "200":
          description: "Successful provisioning of the stackpack"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisionResponse"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /stackpack/{stackPackName}/deprovision/{stackPackInstanceId}:
    post:
      tags:
        - stackpack
      parameters:
        - $ref: "#/components/parameters/stackPackName"
        - $ref: "#/components/parameters/stackPackInstanceId"
      summary: "Provision API"
      operationId: provisionUninstall
      description: "Provision details"
      responses:
        "200":
          description: "successfully uninstalled"
          content:
            application/json:
              schema:
                type: string
        "400":
          description: "bad request"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

  /stackpack/{stackPackName}/upgrade:
    post:
      tags:
        - stackpack
      parameters:
        - $ref: "#/components/parameters/stackPackName"
        - in: query
          name: unlocked
          allowReserved: true
          required: true
          schema:
            type: string
      summary: "Upgrade API"
      operationId: upgradeStackPack
      description: "Upgrade stackpack"
      responses:
        "200":
          description: "successful"
          content:
            application/json:
              schema:
                type: string
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /stackpack/{stackPackName}/confirm-manual-steps/{stackPackInstanceId}:
    post:
      tags:
        - stackpack
      parameters:
        - $ref: "#/components/parameters/stackPackName"
        - $ref: "#/components/parameters/stackPackInstanceId"
      summary: "Confirm manual steps"
      operationId: confirmManualSteps
      description: "Confirm manual steps of the stackpack"
      responses:
        "200":
          description: "successful response"
          content:
            application/json:
              schema:
                type: string
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  parameters:
    stackPackName:
      in: path
      name: stackPackName
      required: true
      schema:
        type: string
    stackPackInstanceId:
      in: path
      name: stackPackInstanceId
      required: true
      schema:
        type: integer
        format: int64

  schemas:
    StackPackUpload:
      type: object
      properties:
        stackPack:
          type: string
          format: binary

    StackPack:
      type: object
      required:
        - name
        - displayName
        - version
        - categories
        - isNew
        - faqs
        - configurationUrls
        - releaseStatus
        - isCompatible
      properties:
        name:
          type: string
        displayName:
          type: string
        version:
          type: string
        logo:
          type: string
        categories:
          type: array
          items:
            type: string
        isNew:
          type: boolean
        overviewUrl:
          type: string
        detailedOverviewUrl:
          type: string
        resourcesUrl:
          type: string
        faqs:
          type: array
          items:
            $ref: "#/components/schemas/FAQ"
        configurationUrls:
          type: array
          items:
            type: array
            items:
              type: string
        releaseStatus:
          $ref: "#/components/schemas/ReleaseStatus"
        isCompatible:
          type: boolean

    ReleaseStatus:
      type: string
      enum:
        - AVAILABLE
        - ENABLED
        - COMING_SOON
        - HIDDEN
        - BROKEN

    StackPackStep:
      type: object
      properties:
        display:
          type: string
        name:
          type: string
        value:
          type: object
          properties:
            _type:
              type: string

    StackPackIntegration:
      type: object
      required:
        - name
        - displayName
        - categories
        - isNew
        - faqs
      properties:
        name:
          type: string
        displayName:
          type: string
        logo:
          type: string
        brandIcon:
          type: string
        categories:
          type: array
          items:
            type: string
        isNew:
          type: boolean
        overviewUrl:
          type: string
        resourceUrl:
          type: string
        faqs:
          type: array
          items:
            $ref: "#/components/schemas/FAQ"

    StackPackConfiguration:
      type: object
      required:
        - status
        - stackPackVersion
        - config
      properties:
        id:
          type: integer
          format: int64
        lastUpdateTimestamp:
          type: integer
          format: int64
        status:
          type: string
        error:
          $ref: "#/components/schemas/StackPackError"
        stackPackVersion:
          type: string
        config:
          type: object

    StackPackError:
      type: object
      required:
        - retryable
        - error
      properties:
        retryable:
          type: boolean
        action:
          type: string
        error:
          type: object

    StackPackList:
      type: array
      items:
        $ref: "#/components/schemas/FullStackPack"

    FAQ:
      type: object
      required:
        - question
        - answer
      properties:
        question:
          type: string
        answer:
          type: string

    FullStackPack:
      type: object
      required:
        - name
        - displayName
        - version
        - categories
        - isNew
        - isMultiConfig
        - faqs
        - configurationUrls
        - releaseStatus
        - steps
        - integrations
        - configurations
        - canUninstall
        - isCompatible
      properties:
        name:
          type: string
        displayName:
          type: string
        version:
          type: string
        logo:
          type: string
        categories:
          type: array
          items:
            type: string
        isNew:
          type: boolean
        isMultiConfig:
          type: boolean
        overviewUrl:
          type: string
        detailedOverviewUrl:
          type: string
        resourcesUrl:
          type: string
        faqs:
          type: array
          items:
            $ref: "#/components/schemas/FAQ"
        configurationUrls:
          type: array
          items:
            type: array
            items:
              type: string
        releaseStatus:
          $ref: "#/components/schemas/FAQ"
        steps:
          type: array
          items:
            $ref: "#/components/schemas/StackPackStep"
        integrations:
          type: array
          items:
            $ref: "#/components/schemas/StackPackIntegration"
        releaseNotes:
          type: string
        upgradeInstructions:
          type: string
        configurations:
          type: array
          items:
            $ref: "#/components/schemas/StackPackConfiguration"
        nextVersion:
          $ref: "#/components/schemas/FullStackPack"
        latestVersion:
          $ref: "#/components/schemas/FullStackPack"
        canUninstall:
          type: boolean
        isCompatible:
          type: boolean

    ProvisionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
        name:
          type: string
        stackPackVersion:
          type: string
        lastUpdateTimestamp:
          type: integer
          format: int64
