# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Topic API
  version: "1.0.0"
paths:
  /topic:
    get:
      tags:
        - topic
      summary: "List topics"
      description: "List all Kafka topics available in StackState"
      operationId: list
      responses:
        "200":
          description: "Topic list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicList"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

components:
  schemas:
    Topic:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    TopicList:
      type: array
      items:
        $ref: "#/components/schemas/Topic"
