# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: Topic API
  version: "1.0.0"
paths:
  /topic:
    get:
      tags:
        - topic
      summary: "Topic list API"
      operationId: listTopics
      description: "Get topic list"
      responses:
        "200":
          $ref: "#/components/responses/TopicList"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /topic/{topicName}:
    get:
      tags:
        - topic
      summary: "topic details API"
      operationId: getTopic
      description: "Get topic details"
      parameters:
        - name: topicName
          description: "Name of the topic"
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "details of the topic"
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: "#/components/schemas/TopicMessages"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"

components:
  responses:
    TopicList:
      description: "list of topic"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Topic"
  schemas:
    Topic:
      type: object
      description: "topic object"
      properties:
        name:
          type: string
      required:
        - name
    TopicMessage:
      type: object
      properties:
        message:
          type: object
          additionalProperties:
            type: string
    TopicMessages:
      type: array
      items:
        $ref: "#/components/schemas/TopicMessage"