

### Lookup for pod all
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 5220580216738,
  "metricQuery": "max_over_time(kubernetes_state_container_restarts[${__interval}])",
  "overrides": {
    "components": 60,
    "timeSeries": 60
  }
}

### Lookup for pod auto
POST {{host}}/api/monitors/identifierLookup5
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 5220580216738,
  "metricQuery": "max_over_time(kubernetes_state_container_restarts[${__interval}])"
}

### Lookup for container auto
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 117353961809006,
  "metricQuery": "max_over_time(kubernetes_state_container_restarts[10m])",
  "overrides": {
    "components": 60,
    "timeSeries": 60
  }
}

### Lookup for pod, limiting time series loaded 
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 5220580216738,
  "metricQuery": "sum(max_over_time(kubernetes_state_container_restarts[${__interval}])) by (cluster_name, pod_name, namespace, image_tag, pod_phase, image_id, daemonset, display_container_name, container, priority_class, interval, image_name, short_image, kube_ownerref_kind, cluster_name, pod_name, container_id, sts_host, kube_ownerref_name, deployment, replicaset, statefulset, kube_app_managed_by, kube_app_version, kube_app_instance, kube_app_name, persistentvolumeclaim, kube_app_component, kube_app_part_of,git_commit_sha, cronjob)",
  "overrides": {
    "components": 400,
    "timeSeries": 400
  }
}


### Lookup for pod http metric
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 5220580216738,
  "metricQuery": "pod_http_requests_count",
  "overrides": {
    "components": 60,
    "timeSeries": 60
  }
}

### Lookup for service http metric
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 167565837194221,
  "metricQuery": "pod_http_requests_count",
  "overrides": {
    "components": 60,
    "timeSeries": 60
  }
}

### Lookup for service http metric with some logical aggregation
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 167565837194221,
  "metricQuery": "sum(pod_http_requests_count) by (local_pod_label_component, cluster_name, local_pod_label_app_kubernetes_io_instance)",
  "overrides": {
    "components": 1000,
    "timeSeries": 1000
  }
}


### Lookup for stackstate pod metric (only 18 metrics), but still 600+ pods
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 5220580216738,
  "metricQuery": "stackstate_stackstate_receiver_element_create_passed_count"
}

### Lookup for stackstate pod metric (only 9 metrics), but still 600+ pods
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 5220580216738,
  "metricQuery": "sum(stackstate_stackstate_receiver_element_create_passed_count) by (pod_name, cluster_name, namespace)"
}


### Lookup for node
POST {{host}}/api/monitors/identifierLookup
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "componentType": 5220580216738,
  "metricQuery": "kubernetes_state_node_by_condition{condition=\"PIDPressure\"}"
}