
# To initialy create a channel open a url like this in the browser. 
# It implements an OAuth flow that requires user interaction, thus cannot be done via a simple rest call
# {{host}}/api/notifications/channels/slack/oauth-redirect?redirectPath=/%23/notifications/new
# Example: https://master.preprod.stackstate.io/api/notifications/channels/slack/oauth-redirect?redirectPath=/%23/notifications/new
#
# The URL that you get redirected to will include the id for the created channel: `?channelId=85019403380238`

@slack_channel_id = 273419503745686
@notification_configuration_id = 244109798388708

### Get notification configuration {{notification_configuration_id}}
GET {{host}}/api/notifications/configurations/{{notification_configuration_id}}
X-API-Token: {{apiToken}}


#### List notification configurations
GET {{host}}/api/notifications/configurations
X-API-Token: {{apiToken}}
Content-Type: application/json

### List channels for notification configuration
GET {{host}}/api/notifications/configurations/{{notification_configuration_id}}/channels
X-API-Token: {{apiToken}}

### Delete notifiation configuration channel
DELETE {{host}}/api/notifications/configurations/{{notification_configuration_id}}
X-API-Token: {{apiToken}}
