
# To initialy create a channel open a url like this in the browser. 
# It implements an OAuth flow that requires user interaction, thus cannot be done via a simple rest call
# {{host}}/api/notifications/channels/slack/oauth-redirect?redirectPath=/%23/notifications/new
# Example: https://master.preprod.stackstate.io/api/notifications/channels/slack/oauth-redirect?redirectPath=/%23/notifications/new
#
# The URL that you get redirected to will include the id for the created channel: `?channelId=85019403380238`

@slack_channel_id = 273980725327401
@notification_configuration_id = 120631240747903

### Get channel {{slack_channel_id}}
GET {{host}}/api/notifications/channels/slack/{{slack_channel_id}}
X-API-Token: {{apiToken}}


#### List slack channels
GET {{host}}/api/notifications/channels/slack/{{slack_channel_id}}/listSlackChannels
X-API-Token: {{apiToken}}
Content-Type: application/json



### Join slack channel
POST {{host}}/api/notifications/channels/slack/{{slack_channel_id}}/joinSlackChannel
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "id": "C061HG00REW"
}

### Send test message
POST {{host}}/api/notifications/channels/slack/{{slack_channel_id}}/test
X-API-Token: {{apiToken}}
# Content-Type: application/json

### Assign channel to notification configuration {{notification_configuration_id}}
POST {{host}}/api/notifications/channels/slack/{{slack_channel_id}}/assignNotification
X-API-Token: {{apiToken}}
Content-Type: application/json

{
  "id": {{notification_configuration_id}}
}

### List channels for notification configuration
GET {{host}}/api/notifications/{{notification_configuration_id}}/channels
X-API-Token: {{apiToken}}

### Delete slack channel
DELETE {{host}}/api/notifications/channels/slack/{{slack_channel_id}}
X-API-Token: {{apiToken}}
